In [1]:
import torch
import joblib
import pandas as pd
import numpy as np
from pathlib import Path
from sentence_transformers import SentenceTransformer

In [2]:
from google.colab import files
files.upload()

Saving sbert_scaler.joblib to sbert_scaler.joblib
Saving sbert_logreg.joblib to sbert_logreg.joblib

{'sbert_scaler.joblib': b'\x80\x04\x95\xaf\x01\x00\x00\x00\x00\x00\x00\x8c\x1bsklearn.preprocessing._data\x94\x8c\x0eStandardScaler\x94\x93\x94)\x81\x94}\x94(\x8c\twith_mean\x94\x88\x8c\x08with_std\x94\x88\x8c\x04copy\x94\x88\x8c\x0en_features_in_\x94M\x00\x03\x8c\x0fn_samples_seen_\x94\x8c\x16numpy._core.multiarray\x94\x8c\x06scalar\x94\x93\x94\x8c\x05numpy\x94\x8c\x05dtype\x94\x93\x94\x8c\x02i8\x94\x89\x88\x87\x94R\x94(K\x03\x8c\x01<\x94NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94bC\x08x#\x00\x00\x00\x00\x00\x00\x94\x86\x94R\x94\x8c\x05mean_\x94\x8c\x13joblib.numpy_pickle\x94\x8c\x11NumpyArrayWrapper\x94\x93\x94)\x81\x94}\x94(\x8c\x08subclass\x94h\r\x8c\x07ndarray\x94\x93\x94\x8c\x05shape\x94M\x00\x03\x85\x94\x8c\x05order\x94\x8c\x01C\x94\x8c\x05dtype\x94h\x0f\x8c\x02f8\x94\x89\x88\x87\x94R\x94(K\x03h\x13NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00t\x94b\x8c\nallow_mmap\x94\x88\x8c\x1bnumpy_array_alignment_bytes\x94K\x10ub\x05\xff\xff\xff\xff\xff\x89\x9eH\xf4\xa1\x08x?\xee\xcd\xad\xba"\x12\xa6?\xbe\x8c\xe8\xd8\xab)k?E\xc2g\x8b)\x9ej?\xe1\x95\xda\xe0\x82\x8a|\xbf\xf0h3\xae\x0cL{?8B\xc5\xd2\xa6\x98d?\xaf\x88qM,}t\xbf\xfew\x16\x8a~\x9br\xbf\xcdnI\xe9\xa4\xad\x80\xbf=\x10\x15\xac\x849w?A\x02A\x96\xec!\x83?\xa4\x05\xa5;5&X\xbf\xa5\x8d\x88\x93\xf1bg?M\'\xb1\x94\xdc\xccl\xbf\x17\xe85\x16\xb3{t\xbf\xdf\x1c\x00HT2\x19\xbf\x04c\xff\xcc\x19\xbd{?\x0b!g\xefw\x12~?g*\x8ex\xdceQ?\x90\x0f~s\xaeho?\xd0\xfa\xd8\x82v\xc8\x1a?\xa4\x18"\x17\xc3\xc6\x82? \xcc6\x1b\xe3vy?$/,O\xb2\xcdR\xbf@4\xd3H\x8b8\x88\xbf\xf8}\xfa\xd70\xa3\x90?\x19\x1d\xb3Q*<v?\x02\x17Y\x82\x90.t?\xef\xc2i\x1b1\xac\x82\xbf8x\x11\x0c:\x05X?X&?\x94-I`?U\x87\xd4(j\xdbq\xbf\xac\xcb\x96\xc25\rf\xbf\x94\x1f\xcc\x87\xe0\x95\xc2>\xbd\x04f6\xa3\x9f\x8e\xbf\x05\x98\xb6\x90\x80\xd7s?\xe0\xe0\x85rM\x84\x06?\xee\xcdg\x1a\xe3so\xbf`\x887\x84\xe7aw\xbf\xda\xf5\xd8ar`w?o,d{\x9eYx\xbflm\x0cf\xb1%\x7f\xbf\xfd\xc2\xbaV_l\x87?\x15\r\xcai\xeb\xbd@\xbf\x05\xb6^\nF\xf5z\xbfC\xfb\x06\xc9\x9d\xcar\xbf\x00\x02\x8f\x00\xb5^\x90?[c\xdf2dof\xbf\xb0.b%Wkb?\xfdB\xabUt\xf3r?\'\xae\xd7\xdf\xcalp\xbf!r\xe9\xb9\xf7,\x87\xbf\xc9KYRa\x8at?\x849.\x93\x8b\xb3\x83\xbfW\x80\xdf\xa8J\x1c\x8b?@\x8d\xe6\xae\xb3\xbdw?\x1f\x08\x94|\x00C\x88\xbfSR\x85>$\x96v\xbf\xfa\x85\xeb\xe9\xd0L\x92\xbf\xbe{\x132l\x9cp?jd\\\x04\xb2\x0f\x86?:\x01\x91\xbdG\xcc\x90\xbf,cD\x1b\x0ey\x84\xbf\x81\xedM\x05\xda(e?r\xe9\x1e\xa8\x93\xbf\x81?LP\x1d\xdf\t\xaas\xbf\xd6V\xe9CEqu\xbfBUJ\xb1\xbaM_?\xe03&]\xdc\xfei\xbf\x8d\xe1\x0c\xdd\xfb\\p?L2qV\xfbhk\xbfC\xf2\xc2\xa8\xd4W\x83?\xf5Oj\x1e\x81\xdd~?\xf7Wb\xd9\xc1*h?.*l\x04]\xdeQ?\xa5\x1ci\xb9\xfd\xf4r\xbf\xe4\xb4d\xbeRZ|?\x10W\xbe-\x7f[\x84\xbf\xdf\xab~\x15oJb\xbf\xdc\xd0\x1eG\xc1}\x81\xbfN\tm\xdc\xc7*\x91?[\xe3+0\t\xc5l\xbf\x97\xe4bj\xb2\xdd\x83?O\xfe\x06\xdc\xb9\x8c\x95?\x82\xb1[\x9a\x8ccp\xbfl\xd1\xcf=\x83\xc3w\xbf\xc0\xa3z\xb7\x16Cb\xbf\x96\xd8\xfe\x19B\x05r\xbf|\xc6O\x17a~\x82?.}\xfft$9f?k\x89\xf1\xd2s\x0c\x8c\xbf\xb3z\xa7\xcd\xa3R\x85?R,\xa4\xedQ5n\xbf\xb7l\x9c\xe8\xf1\xf7c?1q\x89\xc0X\xe4t?\x98\x11\xb0\xf6+\x11{?\xc6pO\xb3P\xf0}?R;\xe9p\x03P\x88?\xc2~\xa8\xbc\x1f\xc7\x9d\xbf\xac\x8b\x89]\xe9Z\x8a\xbf\x8b\x8a\x19$P\x86\x8e?Ux)__\xa3\x81?\x7f%\x04\x007\xeaq\xbf\xea\x9f\x88G\x0b\xf2\x85?\x15+\x1da}\x90f\xbf(PI\xfd\x83\xf2\x91\xbfU8O\xfd\xf7\xfdr?2\x9c\x9f\xdd\x11K\x86\xbf|F\xecZT\xba\x96?p\xff|\xc4\x84\x86d\xbf\xaa\xe1\xf9\xe6/tt?\x85n\x8f\xcd\xd6\x88r?o,^\x0e\x17ls\xbf\x98\x11$p\xcd\x80{\xbf\x13\x14\x191\x83\xa8d?\xb0\x0c\x93\xc0h\xd0}?\x1f\xea\xd79_\x8e`?\x9e\xfc\x0e10\x7f\x86\xbf\xfe\xe8\x844\x94!\x8c?#\xed\xea[\x12\x98\x9d\xbf\xae5\xc2\x10\x04\xf0C\xbf\xf9\xc1\x99\xb4Y\x04r?V\x0f\x02\\\x84\xba\x83?B\xe4\xb2*KO(\xbf!\xd40\xc9\xe9\x01\x86?\xac\x1a\xdb\xb29M\x81\xbfX\xa6\xebp\x11\xebP\xbf\x08\x13l~i\xb7\x86\xbf\xa5:,?\xf1\xff|\xbf\xbc\xe2zny\x18z\xbf\x13\x85c\x86y`{\xbf\x97\xbe\xdf;\x0f\x1eb?Fu\x8eE\x85\t\x86?ff\xe6\xc4\n\x1c*\xbf\xfa\x85\xa6\xa3\xae+\x83?\xd6\xc3.\xad\xa8\xf5G?\x81\x0b\xf5\x94\xbb\x17j?\x94\x01\xa4\x05\xf2\xd6i?\t\x8a\xb9\x9a\xf0\'c\xbf\xdd\x05\xd0\xc5\x8d\xce\x8f\xbfMg6\xce\xccsW\xbf\x11\xfd\xb1KP\x87p\xbf\xc0\xa3\xc9\x15w\xabc\xbf\xf6\xc2Q\x8e\tV\x8e\xbf\xcd\x1f@\xe9%\x14p?\x96\xa7\xad\x0b\x9f\x1a]?_\xf3\xedss\xdbh\xbf\x1cKM#\xdb+.\xbfI\xcb\x8f\x98\xd2\xcb}\xbf]\xbe"\xb5\xdb1v\xbf\xe0\xe0\xdf& \x8dy\xbf\x03.\xd5\x0c^\xd7x?|7gJ\xd95:?u\x17\x95\x04\xd7<\x91?\x94\x90\xaa\xf1\xba\xeb\x93?[T\xd6\x84z\xba%?\xbb\xcfG\x00\x1e\x00e\xbf\xfa\x85N\x86\xece\x8a?\xd9\xa2\x1b;\xaa\x92\x82?\xf79\xb3\xf7\x1a\x82{?\x82\xb1u\x0e5\xccm\xbf\x99\xb7\n\x9f\xe3[Y?\x1c<\xeac\xd5\xad\x83\xbf\xaa\xd3*\xd1\x0b\x1d\x81\xbf \x10\x82`\x07b\x89?1\xc9J\xa7\x8d\x98\x81?\xf5\xcf\xec\x96\xd3)\x8a?\xbe\xbb>u\xa9\x97\x81\xbf5Z\xf2\xb6\xfd\xb3\x85?\xcbD\xd6T\x11\rv\xbf\x14g\xeb\xfe\xe9\xb7v\xbfs\xf0=-\xff"x\xbf\xdb\x0c\xe8b\x93M\x92?\xea\x9f\xdd\xe5\xec-\x81?\xff\xac3,\xfa\xd6g\xbf\xf7\xc9}\xc9u\xc4\x94\xbf\xe1F\xa9]\xf1\x81\x8a?X\x08\xe2\xf8\x9a\xb7\x85\xbf\'\xdd\xbb\xc4\x00X\x91?\xe3\x0e\xa4pO\xbc]?\xdd\x05\xba\xb3\x14V\x1d\xbfj\x94\x9c\x81T\x1e,?\x8d\xc3s\xc8\x8bz\x8b\xbf\xf6\xb1\xb5\x1b\xc9\xcf8\xbf\x16\xd3\xe4M\xe01l\xbf\xdf\x8dI\xa7\x8c+J\xbf8x%j"\x94R?m3+\xcfNp\x83\xbf\x06\xa9\xb9\x9e\x80J?\xbf\x8b\xcaVr\x10\x870?\xee\xaf\x90\x19\xfc"f\xbf\xe3NW\xaa\xb4\x06\x90?M\x14\xe0zn\xda\x85?\x87\xf6\x9d\x8d~\xbc]\xbfN\x98.\x88^\x16y\xbf\xed\\\x9c\x16\xdd\xdd\x7f\xbf\x9d\xa9b\xbe\x18\r\x84\xbf\x00\x0f\x94\x93pSr\xbf\\\x89\xb5\xb9\xf3!Z?\xff\xac\xdf!#\xf2]?\xd5@\xe3\x8f\t\xdf\x91\xbf\xc6\xff\x06\xef\x08hl?\xbb\x0b\xcc\x94j\xe3\x89?\xba\xb8\x83_\xed\tW\xbf\x9ek\x18\xc9\xa5\xfb\x81?z\xeb\xc6\xcf\x90\x12}\xbf\x10W\xba\xfe\xa6\xea\x81\xbf\xb7\x8a;\x9dU\x12q?z\xeb\xe6q$\xdes?lo\xea\xae(\x07q?\xe4\xa5S\x7ff\xfe~?X\xe8d\xd2\x8e\xed\x89\xbf\xb9\xd6\x00/\x9a\xffi?*|\x1d86\xdf\x82\xbf\x81^\xe5L\xd17b?*\xdc\xa6N\x88\tz?\xf9\xc1\x93\xab\\\x92\x86?\xc3\xef\x85>\x0f\xab\x8c\xbf\x12\xeeg\xfc\x7f\xd4\x82?R\x1dTh\xd1\x1ai?;5\x8f.\x0e\x8a\x8b?\xb1\xf20\xefjp\x82\xbf~\xce\xc87\xf3"w\xbf\xafF-ga\xe9\x90?\x15\x9c\xd4\xb7\xda\x0c!?\xf5=\x9f\x9e0X\x8a\xbfa?!\xe4\xeb\xd5U\xbf-\xd7\x82\x06HEU?\xa8\xf7\x8e\xb6\ncG?\x88\xba0\x1e2.c\xbfu\xb5\xc2t\xd3\x98d?)t\xec\x03!\xb3h?qV\xf6\x19\x0b\xbep\xbf\xd7\x0b\xa8\xb9\xcb\x1eq?\xbf\xdfW\xb1N\x9af\xbf\x89~\xd9\xd2?\xff7?\xf2\xa1^\xd4\xae\x02\xa2?\x93\xdb\x99\x97h\xdet\xbf\x9a\xfb\x93\xa8\xc9\t\x91\xbf~\xdd\xe5\x03\x86\x95p\xbf`(K\x0fF]u?\x93j}\xc8\xab\xe5`\xbfO~D\x9d\xdc)x?sn\xa8\x9c\xbf;\x93?\xb3\t\xa6$E\xbc\x8b?J\xf9\x8d=MYf\xbf\x8e\xa5\xbe:\xe7=!?\x8c\x1dg\xbed\xc3\x7f\xbf\x0c\xf4\xa9s\x83\x01p\xbf\xc3\x90\x89\x08\x00\ny\xbf\x11\x8c\x9d\xa1X\xa2g?D]1\xd5\xcbuy\xbf2\x1c\xe7\x98E3j?PB8|\xcf~\x87\xbfw\x90\xcaUi+\x82\xbf\x96m\xb7_R/v\xbf\xbb|\x9fv\x9e\xa5\x83?\xe6<\xf6\xae\xdc\xc8b\xbfQ\x06W\x99D\xd4`\xbf\x05\'O\x9f\x19\xdfZ\xbf\xa2\x9d\xc5Z\x88\x84\x80\xbf\xe2,\x05*\x90mu\xbf&(\n\x8b\xb5cO\xbfpa\xd0\x18[BR\xbf8\x97\xdd\x99\x07\xe7\x92\xbf\xb7\\\xd7\xccc\xbe\x89?y\xfa\x07:\x91\x98~?\x16B\x95\'\x03?K\xbf\xb80\\]\xd0:a\xbf\xae\xf5>\xd5jYr?\xda\xd7\xf6\x07\xdf\xb4U?\xebc\xc0\x9fC\xc7\x83\xbfY\x0c\x94\xf4.\xa1s\xbf~0\r\xc7G\xfef\xbf\xd9\x84M\x99\xabO\x8b?M\x85\xfd\xa2\xb6\xccY?F\xb8\xcf\x1e\xad\xf3|?\xc2\r1b\x95\xfaQ\xbf,\x93\xe2obUr?\x16\xb3\xbc\x07\x96u\x86?Jf\x8a\xf2L\xf4\x82\xbfh\x9b\xd9\xab\x94\xdc\x0e\xbf\xf7\xc8[\x0f:\x86:\xbf\xa6\xe0\xf1|s\xcb\x8d\xbf\x0f\xb3\xfe\x17=U\x85?\xae3e\'\x82\xbb\x7f?[\xe3\xd0Q\x83Ee\xbf\t\xa8Yl :Z?zM\xfe\xb0\x0b4\x87\xbf\xe4a\x03\tP\xa9v\xbf\xf2\xbb\x16\xed\xa7\x89\x85\xbf\xc6_\xda\xc8B[t\xbf\xbe*v\x971%\x90\xbf\xb3P\x19r\x9e\xf7\x80?\x99\xd5e\xdb\x90\xc3\x82?\xb4\xcd\x18\xd8B\x0bk\xbf\t\x19\x0f\x9a\xecD]\xbf\xd3\x86\xbf\xe3\xac#\x82?\xeaL\xedg%-\x95?\xa4\xc9L\xf9\x0cf\x88?\xafj\x89N\t2x?\xcfTh\xbb\xafra?\xf0\x19\x1d|{]i\xbf\xf4\x8b\x14x\x1e\xd7v?\xd0\xfaX\xc6\x8b\xeaN?\x94\xae0\x0bj\x93`?\x9fOm\xff/ns?Wbd"<,\x85\xbf\xcf6\xd0XK\xafv?\x99(K\xbe\xb5\x81P?\xb8Nc+\xa9\x87R\xbf\xfa\xa3\x0f6\x88\x1fy\xbf7\x92\x0bt\xd2\x97}?\xa6\xc2D!\x07\x1f|\xbf\xb9\xa4\xcd\xd5)\x04\x82\xbf\xe6\x9bv\xffM\x8b\x90\xbf\xdb\xbd1\xc2\x85d\x9d\xbfU\xcbO\xb1\x02\x16r\xbf\xae\xe2!\x04\x9b\xd9T?P$\xa2\x99\x1a\x08K?\xc2~\xa0F\x9b\xab_?|\xb7C\xa8<\xea\x8a\xbf\x956FyEaD\xbf\xfe\x95h\xeb\xdf\xce\x83?~\xceBI\xe5\x9a\x7f\xbf\xe4\x03\xb3@\xf1\xe9h?\'\xcem}&\xb4r\xbfz~\xa2t\x05\x06\x91?q\x83\x88\xfeW%}\xbf\xd0:\xb7\x82\x98\x17v?\xeb\xf2mU-\xf0`?\xbc\x93\x13\x05S\x91z\xbfE\x12A\x19\xfc\xe7V\xbf@\xdc\xc3\xcfj\xbe\x88\xbf\x0b\x12ss\x0b\xc4m\xbf\x88\xc9-G\x1a\x19}\xbf\xc0\x14$\x1b\xe9\x00T\xbf\xf6\x04X\xb9\xbb\xaa\x8a\xbf\xaf\xa6}\x19,\xa6^?\xd9@7sI8\x80\xbfBUd\x7f\x85Zr\xbfpa\xc2D\xae\x12p\xbf\xb5\x02e\xd3\\\x8f\x85\xbf\xbb\xcf5H\xd9Q\x8a\xbf\x08\x02\x82\xcf,\x12\x8b\xbf\x87\xf6\x99\xa1\r\xe3`?\x86#\xeb\xd5u\xf4\x80?|7\xf3\xd1%\xa7u?\xcfT\'n\xb1\x90\x81\xbf\x89~\x12\xe8\xdf\x9e\x8f?\xa0\xf5\xc1\xcb\t\xb7#\xbf\xb5[\xa4\xe7\xd7}T?A`\x00\xcbt\x9fa\xbf[\x03k?\xa8\'\x8c?\x9b\x1a\x06\xcbR7\x8c\xbf\xb1\xf2(\xcf=\xdc\x8b\xbf8\xe9\x05~\x81Ap\xbfr\xcb\xbaJ\x1d\xd0~?\x82@d\r\xdf\xc6W\xbfMg\xd4\x9d\xd0B`\xbf\xdc\xd0Y\xa4}\x1c\x8f?\x97M`>\x1f#T?D,\xc5\x16\x1dJ\x82?\x07M\xb0R(\x1db\xbf\xc4\x95\xd0\x84\xd1\x9dp?\xab\x07\x92m"\x91}?$\x11\x83E\x99\xf5t?\xc6p\xf0\x1b\xe7Ss\xbf\xcc\xea\x11WP\x88N\xbf\x8a\xe6\x183!Tp??\'\xa0\x08\xe8)c\xbf\xef\xe4\xc9_\r=u\xbf\x10f\xdd\x14\xd3\x9c\x80?\xa5\x1c\xb3\xb3\xe7\x19}\xbf\x87\xf6\x06\x85Y\xdd\x8b?\x98 \xa4\x0fq\xb5\x82?\xbd\xe6N\x86g\x9ex?\xef\x02\xbd\x1b\x9a\x90<\xbf\xde:I/:\x937\xbfN\x0b\xc7\xf0\t\xf5\x85?\x0cGGt\xcb\xba\x9e\xbf^/\xd5/\x96\x03\x94?\x7fe\xd2\x87\x1f-J?\xb3z\x82\xe2\xc2\xb7v?\x91\x92H\x9c\xe6^\x85\xbfE\x12\x01\xb1\x95\xccJ\xbf\x01S\xd4p\xc8\xcaY\xbf\xcc\x08\xa3\r\xab\xa1\x85?\xad@\x1f\xact\xa3z?L\xa3,\xc3\xc9\xb8_\xbf\xf3V\x9aP<Nu?\x1c\x9ec\x8a\x8e\xa5{?\xb4/\xa3\x8f^\x82h?H\xb1\x0e\x05\xdaTf\xbfFG4M\xe2\x94}?\x13\x14!\xeb\xae~a?\xe5\x07\x03h\x94\xa2T?y\xa9\x1cR\xc7Du?\x9b?--\x8b}u?\x87g\xd2\xc2h\x98\x83?\x93\n3\xac\n\xda\x7f\xbfM\x14\xfa\xe6\x9e\xcb\r?\xc1v\x12f%\\R?}\x19i\xc0\xf3\xd1s?%\xd55\xeeh\x17p\xbf4\xb6~=E\x07\x7f?\x0b\xff\x93\x94\x10\x10\x91?\x1b)[\xa2\x92Vs?\x04\x81\x85X)Xt?=\x9f\x96\xe9,\xfcp\xbf\x87\x85\xb0\x1d\xf7\xecg\xbfL}\xf1\xdf2~\x86\xbf=\x9f\xcb\x9e\x8c\x1ef\xbf\xaaC$;\xc2HI?\x9c\x92\xeaH\x93\xa9.?TF\xdcQ~\x7fw\xbf\xeeo\xce\xed\x14\x13\x8e\xbfp\xd2=\x06\xb7\x13r?\xad>\xe1y\x1c\xbe\x8c?Bs\xc7\x94\xaf=G\xbf\xc4$\x1c\x9d\xc6\xc2e?\xb9e\xb4#\x93\xa3f\xbfI\xe2\xed\x07\xcd\xf4p\xbf\xbe\x8c\xd1\xfb\x88s\x92\xbf\xe6Z!{\xba;x\xbf\xadq\xa8\x00#G\x86?m\xa4\xab\x0e\x80\xbfi?DN7\xbd\xd4\x8bh?\x9e\x8cE\x00\x1d\xd5q\xbfX\xa4\x1c\x07+\x98\x87?Yy\x82\xa9\xd8\x99y?\x1e\xc4\xd8HE7s\xbftS\x82 \x82\xefO?v\xbd/\xe6=\x06\x8d\xbf3\xe0"n\xca\xd9`?M\x14\xfd0Lt\x80?\xe9j\x82\r\xb3\x88Z?E\x83\x0f+\xc51\x84\xbf\xbd\xd7\x9c\x03\xab6\x85?\x1eS\xb6-\x06\x03y\xbfvj\n\xef\xb3\xb8|\xbf\xfdB\x00\xfa\x04\xb4|?\xc7\xe1\x81\x88\xc3\ty?\x19p\xe8g\xec\xd0\x84\xbf\x80\xd8c\xd55\xa0\x82\xbf/A\x0f\xf1\xad\x85{?\xf8\x8c7\xd3sVq\xbf#\xdc\xd4\x02\xb8\xa1q?\x1fj iT\x82p?\xac)\xc9C\x8bj\x8a\xbfl\x8a\xb4Wx<\x91?\xb9\xf4\xa6\x93\xca\x0bt\xbf\xae5\xd1|\xcf\x08y\xbflo\x14\x91\x17\xdcu\xbf\xa4\xe7\xcdP\xaa\xabs\xbf\x96\xfay\xbfBa\x8d\xbfu\x08%D\xa8\x0cv?\x8d\x92\xbc\xf8?\xb4t?q\x16cV\xbaz\x9c?\xad\xad\xe6N\xc6e:\xbfC\xda\x84=\xce\x18u?\x0f!\xa7d\xf3e`?\x7f\x12\xce\x95\x1c\xde|?,\x93\x16\xe8\x9cvs?\xb7\xf5/$9\xdbu?(\x92\xa0\xfe\x97\x16o?\x9d8H{~Uj?\xdf\xfeF\xa3W\x8b~\xbf\xd6\xc7F\xa3\x97\t5\xbf(\x92>\xf7\\ty?\xd9\xc0\xc7\xd9\xd05\x00\xbf\xbduz^\xb5\xefz\xbf>\xf2\xe3\x97Y\xe8=\xbf=\x9e$\x18p\xe8\x81?\x1a\xd2\xe2h`\xed\\?Y\xccv\xeb\n\xe2\x88\xbf\x8e45\x9d\x19\x92\x8f\xbfW\xb1?F\xbb\x8b|?\x02jf\xb9\xf6i^\xbfz\xaf\xfa\xbca\xce4?\xc2:\x8eW\xb2\xc8\x81?\x9e\xdeZ\xdf)\x8ct\xbfBU\xd6\x7f\xeb\xafj?h\x1f\xe9\xf4\xe4m}?V<\x0c\xa5@\xfb\x85\xbf\xdfm\xe8|R\xc7p\xbf"\xa5\x12\xe6p\x90e\xbf$\xbe\x97~\xb8\xe6T\xbfU8\x010\xc5\x8d\x96\xbf\xde\xe7pRM\x99\x8a?\x9b\xce\xbf\xd5\xc4>q?=.\xcf\xdf<\xb3\x91\xbf\x86\xc1p\xe8Y\xfew?\x0cG\x138\xae\x14|\xbfZ. L\x9d\xbd\x80?\xb0}v\x8dm\xee\x80\xbfa\xce\xb3\x04\xcf\x86\x9d?,1\n\xb1#bX\xbf\\6\x99\xd5\xdfQf\xbfi#\xcf\xa7\x95(w?\x07\x87\x92\xe2<\xe5d\xbfWSb\xfb\x0b(a\xbfKn\xfaH \xa9\x82?\x91b\xa9\xea\x85\xa8Y?\x96k\xfd\xe7\xcf\xcb]?I\xc4N\xdalkl\xbfG\x0b\x0eBMo|?\x80Gu\x8d\x07\xfdv?|\xe4\xc5}\xc8\xe6e?c\xc7\x0f\x94#\xb5K?\xd8O\xd2\x06p\x1f\x86?\xfe\x06O\xb1\xd5B\x8d\xbf&\xb7\x98\x97\x14\xa9\x97\xbf1:\xc2mt\x0b.\xbf(\x92\xc8\xb3dCL?\xaeT\xb6pg\xc3\x96\xbf\x0f\x93\x00\xe3\x90\xeeq?\x0c\x16\x96i.M\x84?V\x9eLSS\x1ey?\x11\xfd\xa2ry\x87d?c)\x96O\xa1\xecG?C\xfbT\x1da\x87~?!c\x15e\xfd\xc9\x88\xbf\xc2\xad\xc3o]\x87q\xbfx\xb6\x80$\x0fu`?\xa73\x8b<\x0b\x1a]\xbf\xa2\xd0\n\xf7\x0c\xeao\xbf\xa4\xc9\xf1.nH\x8b\xbf\xb9\xe3\xa4l\xa0\xda\x81\xbf\xb9%\xec4e\xfd\x92\xbfQY\xb2\xc4\x9b\x9aa?\x8d\x92i=\xd8X~?\xcbs\xa0\xdd\xef(h?\xec\x98\x15\xfd\xac\xa2\x7f?\xc2\x1c\xc0h\xf8\x12\x89\xbf\xd50)\x8b\xa1f\x81?l`\x1d\x06@\xa7x\xbf\x9b?\x86\x1d\r:d\xbf\x17w^\xa0/\xabv\xbf\t\xc6)2\xd9\xd6\x94\xbfr\xfb6\x0f\xe7.\x90?\xeb\xd4P"\n\'a?\xb5\xa4aloAw\xbft\xe2l\xf8\xd1\x04`?]My\x86M\xe4o\xbf\x834\xde&0lw\xbf\xbc"\x88\xafF\xfew\xbf\x91\xf5<\xba\x08"r?\xd9\x04Dn\xab\x93\x84\xbfb\xf2\x05\xc5\xd2\xefp?\xefU=B$N!\xbf\xc5\xf9\x18\xe8\xff\xb3\x8c\xbf\xa4g\xe8\xb3\x91\x99{\xbf\xd8\x8d{\xbf{N\x94?\xf5\xcf\xfa$\x02\x04>\xb9\xee\xafPS1Eh?7Cr\x84\xfd\xb6~\xbf(\x92H+\xc9\xb3n\xbf\x02[P\xcbyT\x85\xbfr\x18q\x0e\x0fL\x9d\xbfJ\xaa\xad\x89F\xecj\xbf|7\x07\x07\x05\xcf\x84\xbf\xacZ\x8aW\x89\xa0D\xbf\x08c\x9b\xf5\x90Q\x91\xbfc\xe5\xbd\xff~\xa7\\\xbfz~\x95f\x9a\x16n\xbf\x9a\nU\x87\x9c\xffk?\xdeX\xa6\xd1\xd9ox?\x16`k\x93=\xbdk?\xa4\xd7\xf7\x0f\x84\n\x89?\x9c\x04\x847}\\\x96\xbfS\x8e\x1d8\x10\xcdw?\x97\xdcF\x87\x155\x7f?9\xadG\xea\x1bxr?s\xada\x99\x014e\xbf\xfa\xa3w\xcc/\xf78?\x05g=\xbb\x81\x0b}?kI\xf8Y7\x15\x84?a\xb0\x8a2\xa9\xbc\x90\xbf\x8e\xf4\x9f"\x83D\x93?\x0f\xb1yn\xd0&]?\xf6"\x07\xf9E\xf9o\xbf\x9fQx\xefF\xc0\x8f\xbf\xb8\xa1rh\x8ec\x8e?z\xeb\x1e\x06!I\x8e\xbf\xb5\x02\x98vc\x97v\xbf\xdd#\x85\x98\xe0\xf4q?\xc5\xca\xb1=\xe31g\xbf\x00\x013\x11T+\x9e\xbf|UG\t9b|?\x00qLtD5\x95?mBG\x06\x0bd\x85\xbf\xf1{\x05#\x8f\x97\x84?\x94r\xdeI\x1ejv?\x9f1\xa8\xd2\xb9\x90Q?\x13\x14\x0e\xbd\xc1\xafi?\xe4e\x15\x9d\xe7\x07\x80\xbfJV\x17\xd5\xf1{{?\xd4\n`I\\\xbd\x88?\xe859\xcc]\xc7n\xbf$\xbeo.<\x0ch\xbf\x1e\xd3~U\xe0\x1as\xbf\xe0\xe0\xfd\x0e\xf87\\\xbfc8\xac\xeb\xc0hw?cV\xfd\x95\xac+p\xbf33\xf2&\xabZ\x80\xbf\x83u\x1bZ\xe9\xc1i\xbf\xe2lB\xc8Y\x1c\x91\xbf\x80\x07w~\xe5\xa7\x8f?\x10u\xce)\xc6\xe0\x95\xbf\x109\xd2s\xccrt?J\xc8\xb8`\x90$+\xbfR\xca\xa5P\x10v\x8a?&\x19\xc1\x828t\x97\xbf\x16\xc28\x98\x11\x18x?\xa5\x8dT\xc5(6K\xbf\xaeS\xads.\x99z\xbf\x11\x1b\xb6\xa6buz?]\xbeP\x1f\x11\nu\xbf\x11\x8c7\xbc\x15M\x87?S\xd2\xe9\x8f\xad\x11{?\x0e\xcfVw\x98\xffN?\xf2\xb2[M\xaf\xe3|?!\x81}\xf9\xa18\x82\xbf\xa6\xc2U\x95\x81\xce\x81\xbf~\xddUw\xdc]y?5J\x8c\xcb\x90X\x8a\xbf\xb1\xf2\xf5v\xb2\\o\xbf.*&XV\xc5\x90?\x9e\x8b}\xa3\xf1"\x89?\x0f1\xf7\xad\xcb\xd7\x84\xbf\x88\n\x00r\xd93\x89\xbf\xde\xe7\x14u\xf0fd\xbfP$Q5x\xd8p?\x1f\x88\xa9\x83^\x94\x84?N\x9c\x7fHbna?\xee\x8d\x8cy&\xcfv?\xed\tf\x87\x9a_\x8f\xbf,\xb1K\xa6R\xc2p\xbf\xb1\xc1\xff6\xe8\xcbw?\xff?\xe9\x1cJ\xea\x99\xbf-\xd7\xe3I\xb7\x8c\\?\xc8\x16%/\xd2]V\xbf\xca^\xbf\x1d&\xb3g\xbf\x88\x1c\xcf\xc7\x14<\x81\xbf\xa2\xce\xaf\r\x12\xff\x99\xbf7s\x06a\x13\x84\x87?\xecX\x1ao&]g\xbfE\x12!\x1c\xbc\x12a\xbfW\x80i\xe2+R\x1e?\xee?\xc4\x1e\xb04\x82\xbf\xb0.}\xb1\xac\xe8p?\x88I\x07?\xa4\xf9t\xbfN:\x12rB$q?tSU\xc8\x95\xadu\xbf\x04\xe3\xe8\xff\x84^q\xbf\x821\xdaC*\x19v?\xb2\xc3\xfcw\xe9\xfa\x85\xbf\xd9\xa2r\x8f\xfd\x18B\xbf\xa9\x8cjs?\x98\x8f?"\xd8\xf9\x12)\xcf\x82?\xa8V\xceX\xe6\xee\x87\xbfd\xfc^4\x1e:t?\xda\xf5\x95"\x81l^\xbf\xd1\x99\x9e\xcb\xae\xe8p\xbf,\xf5\xaf\xf8M\xe4n?\xfd\xb35\x16\xbd\xbab?C\xfb\x02\x99\xf3\x9dx?\xa3\xc1\x7f\xad\xef\xd7w\xbf\n\xcd\x03d\x0b>\x80\xbf\x93*\x1f\x92\x94m_\xbfiA\x8f4\xed\x05|?h\xad}\xe0\xf7y\x93\xbf\x7f\xa1\xc7\x92\x14\xff\x8d?\x1c\x8a4,V\xd2\x83?\xd0z=\x06\xb0,y?\xf0\x19(\xba\xdb\x14r\xbfM\xf6I\xee\xf5\xb9\x81\xbf\x8dp\xf4l\xdf9K?\x80)J\xb7^"]\xbf}\x1916\x92\xb3=?\xa6\xc2\xb7\x00\xb2\xfdK\xbf\x9b\xdf\x7f\xc9\xe8\x8e\x86?\xf7)>\xc8\xfb\x10{?u\x17Lt\xcaJ\x8d\xbf\xcer\xff\xfa\xdcXc\xbf\xa3\x94\xf2\xdf\x97\xee\x89\xbf\xa4v.b6M\x93>s\x00<\x92\xe0Ur?-fh.1JN?\x88\xba\x17\xf1j\xf5C\xbf\xad\x9ev\x98\xdb\xab\x82\xbf\xe3\xf0\x145\xf6OB\xbf\x81\xfc\xee\x07\xfa\xed\x90?c)D\xc7k\x85l\xbf\xd3"\x8f\x82 P\x8c?\xa8\xba\xbfH^\x8d\x83?Z\x01\x06\xf9\xa7}6\xbf =\x89\x19\x08\x8b\x89?\xe7\x1e}\xa3\x8b\x80<?\\\x89IZ+\xdcP\xbf\xc1\xd8\x19\xcb`\x04D\xbfQ\x95Fj\xf1\xb3_\xbf\x0f\xf3\xb1B\xd2p\x8b\xbf\xc4\x95\x98\xe9\xb3\x07~\xbfUiC\xfa>\x05`?a\xec\xc8=i\x9e\'?\x1f\x08\x0cG\x11F\x88?\x12_\x10\xb1\xbd\x8b\x91?1I\xd4\xa5\x14\x84\x83\xbf\x0c\xf4\x92Ua\rk\xbf$\x11Ri\xa4\xc7}?O~\x0f\x87f\x13q\xbf:\xe2\x10\xf3i\x82\x82?\x19\xe1"F\xaf3.\xbfu\x88\x96`\x89(\x90\xbf\xcb\xa29\xa6\xa2W\x80?\xbb\xbcKg[\x10|\xbfj\xe7\xe8\x8f\xaf\n\x83?)\xd6\xb5+\x8c\x15`\xbf\xa7dB\xb7\x82\x82|\xbf\x122\x16\xb69z\x93\xbf\x0ce4c\xd4\xedf\xbf{ Nc\xf6sv\xbfv\xba\xc5\x9f\xff\xe3\x90\xbf\xe8\x04+K1I\x90?\x96xI\xae\x87\x0b\x81?`{IU\x96\xe0i?N\x9c\xfc\x9eTr\x8c\xbf\x1c\xb6\xadD\x17T\x82\xbf-\xd7\xb2\xffE\r|?\x89Q\xbc\x86\x94\x8c\x83\xbfJ\xe6\xe4-\xe73x?\xc1g &\xb8\x98o\xbf%\xf3\xb4P\x04\x92\x81\xbf\xb80\xd9vK\xf5\x85\xbf\x82\xcf&\x893\nh\xbf1\xab\xcf)Q\x98Q\xbf\xd9R\x9aI\x84\x8b\x83?\xfe\xc4\x96\xd8\xce\xef\x8c?\x1db].XA\x93\xbf\xc2+"*(#D\xbf\x1eD\xcc\x92\xa9\xcar?;\xa6\xae\xc7\xe9\x13g\xbf\xd4\xfb\xa2\xc6\x0c\x04\x81?\x18\x1a\xdd\x13>mz\xbf,1\xfcM\xcb\xa20\xbf\x03=\x988v\x0f\x7f?\xe5\xc7\x95\xed\x15s\x80\xbfY[3\xb8\x9e8p?\xbe\xb9\x1br\xc3\xe8q\xbf\xaci\x87\x99K+\x90?\xabV\xd7\xff\x03\x94v\xbf\xe1\xa4\x9dJ\xefau?\x8a\xe6\xd2\x0c\xd2\xe1\x80\xbf\x89~\xa1\x8e\xc6\xed\xf38\xe7\xf1:b!\x8at\xbf\x88\xba\x0b\x1fE\xaa\x04?\x8a\xe4\x99a/vz?\xb3\x98J\xdc%%\x93\xbfS\x8e\xc9\x8f\x13\xb8R\xbf\n\x8c\'\x06\x9823\xbfE#_\xe2\\>v\xbf\x14\xba\xcd\xc4H\xbb\x7f\xbff\xf43!\xb5Y\x86?%\xd5\xc6\x9b\xb3\xd4\x80?\x0cG\x13\xcd\x90FX\xbf\x95+\x00\x00\x00\x00\x00\x00\x00\x8c\x04var_\x94h\x1b)\x81\x94}\x94(h\x1eh h!M\x00\x03\x85\x94h#h$h%h(h*\x88h+K\x10ub\x0b\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xd2Q9\xae\x9f\xb9S?\x8d\x8c\x12\xa5\xa4Bd?\xd0-\xfb\x13\xdb?A?\x7f\x99\x84\xd6\xa2\xa3R?:\xbcK\xfd\xcaIS?\x1eF\xec\xdb\xbb\xc3F?\x17\xbb\xd5\x10\x05M[?~\x19\xbb:"]Q?\xfb{;-H\xc3[?\xd7\xf98^\xfb0P?\xc4^\xb2\xfb\xf1\xc9W?$\x89\xe1\xdb:\x15^?IC\xf0\xab\xd72Q?vZ\xd3\xdc\xb8\xe3]?\x91*\xf8]j\x13R?\xf0\x03\xe0]\xe2\x81[?\xdd\xce\xb2<\xf2\xc1N?:\xf3\x83\xd1=\xf9R?o\x01\xbc\x84D6[?\xb7\xc3\xd3\xde\xe19E?\x88q\x8b\xcb\x9b!P? 0\xa2\xc7\x12eG?d\x14\x00\xda\xc4GO?\xdf\xa6\x9a\x86\x91\xc3I?\x93\xe8G\xb2\xce4Z?y\xfa\xd7\x15h\xd2M?iu\xc9\xd5\xa8BT?\x15o\x9b\xcf\x97\xb4Q?"\x81}N!\xd9R?]\x86\x05\xba\xa0\xbeV?\rV\x143\x9cNY?\xde\xda\xc9\x90\xf2<R?\xd2{g\x96\xcc\x0fQ?A\xc0\x8c)x\x94X?-\x1c@\x99X\xb3;=-\xc1\xde\x08_\xd2K?vt\x1f\x17f\x17P?\x90$\xc8\xc8\x10\x1dG?#\xcc\x12\xdc\x19-Y?<\xf4\xa8\x90\x9e\xd2Y?\xf5\x96\xe7\xa4\xc5\x90[?\xd9\x08\x0fE\x10\x87a?g\r\xae\xd6\x1d\xadL?\xc5M0F&2I?a\\\xfa\x16\xf00L?\x85W\x0fg*\x0b]?qd.\xb6\x0f\tQ?\xac,s9)v[?\x05v\xce\xcc\xf4~X?\x1d\xcd\xe1\n\xaa6S?\xca\xd8\xc2\x99cu4?\x91<\x0b\xe2<\x1b\\?z\xde\x1a\x17"\x88X?\x1bEI&*\xd9E?\'\xbdn\xc18\xd4a?\x87x^t#\xb3`?\xce<\xf3\xf3\xeb\x1cF?\xaf\xd8ZN"\xcd\\?Z\x98\xca\xfd\x05\x18^?51\xedF|\xdbZ?\xba/\xdd\x9bCDT?kl\x11\xd8[SS?\x01\x8e2(|kG?RT\xc0$\xdc\x11M?\xd5\x96t\x1fw\xb0`?\xe2\tr\x07\x9b(P?\x07F-\xc14\x1f[?\xf6\xa0\xbf\x91\xac\xb0W?\r8\x81\xf2\xa4\x87M?K{\xbd,\xeb\xdeO?\x1de+\x9ck\x80\\?\x08n\x0531\xa7L?\xf2w\xb0\xe8r\xf4I?x0\x14\xfb\xe2fP?\x00\'`\xba\xc7\x96Q?P\x96\xed\xcek\xbdZ?\xd2\xec\xc8\xa4#BJ?\xe8\xfcPjJ\xa5U?\xde\x19~\xdb\x8e\xdfQ?\xab\xe3\x00\xf2*KE?w\x9f\x19\xd2\xcc\x1b]?\xed, \xd3\x96\x15W?\x83c\x9bUp\'D?\x93\x1fW\xb4\xcfGQ?$\x17`\xbb?\x1cX?\x94\x80VEM\xff`?\xcc)Y\x8f\xe2"C?\xb9\x14\xb0^\xda\xadI?\xb9\x94\xd8\xcd+WV?\xce\xe1jC\xfdSR?\r\xab>\xb2\xb0\x19`?\xc9<?\xdeUWP?\xbf\xfd\xee0\x83RP?\xa4W\x0e\x83q\xcaM?\xe1n\xb5)9ET?@"\x8d\xe4\x9f\xc1D?\xb7\\\\Cj\xdbN?\xe9\xcb\xb4\x85\xc0u^?\xb9\xfeMX\xcf\xc8P?@\n\x92\xb5\x1a\xb1\\?<x\xb9\x16%#]?xnf \tzL?\x94k?\x94\x08\x1eY?%\xe5\x143\x85\x94I?:\xe6\xe3oX\xf1X?\xc7\xadJ\xf8\x85\x87Z?\x84j\xc8KE\x9dW?\xf3\x04\xe36\xa0\x04[?\xa6\xe9Ro:\x97P?\xd8\x88\xaa#\xe2\x97V?72\x8e\xae\xfb\xc3T?\xdb\xae\xbf\xbaK\xf3J?~h\x1a\xf2c

In [3]:
PHASE2 = Path("/content/phase2_output")
PHASE2.mkdir(exist_ok=True)

import shutil
shutil.move("/content/sbert_logreg.joblib", PHASE2 / "sbert_logreg.joblib")
shutil.move("/content/sbert_scaler.joblib", PHASE2 / "sbert_scaler.joblib")

# FORCE CPU — THIS IS THE KEY
sbert = SentenceTransformer("all-mpnet-base-v2", device="cpu")

clf_sbert = joblib.load(PHASE2 / "sbert_logreg.joblib")
scaler_sbert = joblib.load(PHASE2 / "sbert_scaler.joblib")

def sbert_score(text: str) -> float:
    emb = sbert.encode([text], convert_to_numpy=True)
    emb = scaler_sbert.transform(emb)
    return float(clf_sbert.predict_proba(emb)[0,1])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [4]:
sbert_score("This is a neutral test sentence about autonomous vehicles.")

0.8182324485373564

In [4]:
from pathlib import Path
import shutil

PHASE2 = Path("/content/phase2_output")
PHASE2.mkdir(exist_ok=True)

shutil.move("/content/sbert_logreg.joblib", PHASE2 / "sbert_logreg.joblib")
shutil.move("/content/sbert_scaler.joblib", PHASE2 / "sbert_scaler.joblib")

!ls /content/phase2_output

sbert_logreg.joblib  sbert_scaler.joblib

In [5]:
sbert = SentenceTransformer("all-mpnet-base-v2")

clf_sbert = joblib.load(PHASE2 / "sbert_logreg.joblib")
scaler_sbert = joblib.load(PHASE2 / "sbert_scaler.joblib")

def sbert_score(text: str) -> float:
    emb = sbert.encode([text], convert_to_numpy=True)
    emb = scaler_sbert.transform(emb)
    return float(clf_sbert.predict_proba(emb)[0,1])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [6]:
sbert_score("This is a short test sentence about cars.")

0.5880058681941354

In [55]:
files.upload()

Saving argrew.zip to argrew (1).zip

{'argrew (1).zip': b'PK\x03\x04\x14\x00\x00\x00\x00\x00\xc2Z\x95[\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x07\x00 \x00argrew/ux\x0b\x00\x01\x04\x00\x00\x00\x00\x04\x00\x00\x00\x00UT\r\x00\x07\x04\x8bGiD)Ii\xe8\x8aGiPK\x03\x04\x14\x00\x00\x00\x00\x00\x80I\x95[\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x15\x00 \x00argrew/C_ANNOTATIONS/ux\x0b\x00\x01\x04\x00\x00\x00\x00\x04\x00\x00\x00\x00UT\r\x00\x07\x88lGiD)Ii9lGiPK\x03\x04\x14\x00\x00\x00\x00\x00ZK\x95[\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1e\x00 \x00argrew/C_ANNOTATIONS/D1_to_D2/ux\x0b\x00\x01\x04\x00\x00\x00\x00\x04\x00\x00\x00\x00UT\r\x00\x07\x04pGiD)Ii9lGiPK\x03\x04\x14\x00\x08\x00\x08\x00\x8aV\x93[\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00H\x00 \x00argrew/C_ANNOTATIONS/D1_to_D2/Annotation_2018argrewrite_100_NEW.txt.xlsxux\x0b\x00\x01\x04\x00\x00\x00\x00\x04\x00\x00\x00\x00UT\r\x00\x07\x0c\xe1Di\xf6\x8aGi9lGi\x9dXuTT\x8f\xb6\xa6ch\xe9\xee\x0e\xc9\x11\xa4S:\x04A\xe9\xee\x92\x1e`\xe8\xee\x96\x96\x0e\xe9\x8ea\x90\xee\xee\x16\x86\x12$\x04Q\x04\x04\x1e\xfe\xee[\xeb\xaa\xf7]\xffxgf\x9f3\xb3\xce\xf9\xf6\x9a\xfd\xad\xfd\xcd\x0eu%D$\x0284448h\xa8\xa0*\xdc/\x07\xde\x83\x99;\x99\xa9\xbb89\xbb>6sr\xb1\xe0\xf2r\xb0\xafJ\x9cV\xec\xe5&\x08;\xbd!\xa0\xbd<\xb6iW\xe1o\xa4,\xc0D\xea\x0f\xa4\x8c\xf2\xa4\x15m\xeeg\xc2Rh\xfcr<\xde\xfeJ\xa3\xe3\xe2|\xe7\xfe.\xbeW\xa1s\xa3"\xb7\xa3\xd0}=\x0fc$)\xe5\xd1\x9cK\x99\xf0:\x81\x9b\x8e\x03\xcc\xb5\x9d\xab\x90\xe5Mp\x7f\x15%\xa6\xee\x87|\xfa\xfcb\x03I\xbdS,T\xe7zYF\xfdG\xa6\x94Io\xba\xd9\xb6z\xad\xc9\xb9\xa5:\xa3Ph\x95f\xf9\xd4?\xcarv\x04\x04s\x02\x1b\xe2\xa8\xc0\xfa\x99\xfe:\x0b.\xda\x99OV\xd5\x82t\x11\xbe\x95\xa9\xfb\xa0r\x98|\x1e\xf7n\x1c\xb9}\x95\x9e\x94\xb1\x06q,\x19x\xad<\xd0\xdf\x17\x1aK"\xb2\xbe.\xa6<:\x98\xe3ah\x1d\xd9\x18\x836\xac\xe6\xc1\xc5\t\x88\x17@\xc7>\x11\xc7$\xba`\x07\xe9\xeb\x1b\xe8\x90\xebZ\xb2B"4\x89\xacF\xd9\xcc|\xdb`\xec\xdf\xb2{k\xee\x86A\x14\xa8z\x86a\r\x8d\xf2\xcd\x97OP\xdd\xfc\xe2\\\xbe_\xb9[\\\xa0\xab+\xa1\xa2}\xcar\x17A\x86\x87\x83\xbbx0\xf5\xff\xca!\xc6\x83\x19\xb9X\xd8\xbb>\xe6\xfay\xaeJ\xeaV\xed\xe5\xc6\x0c;\x05G\xb1\\\xce\xaf\'\xe0J\xa9xJ\xcaCT\xacE$\xe4\xd7\x80\xb6\xf8\xcf"Qw\x8f\xd1Q\x91\xa41=6I\xf6/\xf7\xd5\xeaW\x8faVg1\xac\xc2\x00\xc5\xeaOr\x00\xcc\xb0J\x8c\xe0\xa4\xf8\xf0\x9b\xf9\xd85\x8f\x17\xf3b\x9b\x95m\xe6\xe7\x1fM\x89\x8aY\xcd\x19\x9f\xedya$\x8cG\x18\xeeg\xd2\x85\x9d\xcfj\x9eg\x8e\xf2a\xe16e\\\x04\xd4\xdad\xda\xc9\x1b\x91\xd6W\x84\x08vG\xe5\xbc\xe0=>\xd2\x8d\xea\xb5\xebS\xfa<w9\xb1I\x99Q8\xd8%\xae|\x95\xc6b\x9e\x83b\xce\xf8\x86\xd4\x90EEMF\xd3 \xef\xd1\xc4\xa1\xfd\x9d&*\xf1\x80\xf1t\xb5)\xdbm$\xe5\x9e\x1a\xb3\x92\xa5\xd1\x08\xa9[\x8c\xbf\xbc\x81\x01\x97\xbb\x1f\xf2fb\xd3|e\xb7z\xcf\x87\xd4\r|jU\xcel}i\x1d(\xfcOntX\x0c\xe9\xb7\x1f"\x97C\xf8\x1b7\xf8\x0f\xa6\'\xed\xe4\xe8f\xe1\xe8f\xa4\x05r\xb6p5\xf8\x99aM)\xa3\x8e=\xdc\xb8\xb2\x97W\x80\xd1U6`m\xd9;\xb6@Y\xeaQ\xa2\xf2\x0bD}\x1f)\x8e\x1fI\x0e,?\xc0\xcc\xf9N\x84\x006\x83W\x0bk>\x93\xe3,.\x02\xaf\xf4\xa4\xb5q\x93\xbfU\x97H\x03\xf3\x90\xb2/\x14! \x15j\xab\x96]\xe4\x9c\x98\xe8\x82L\x07\x04\x86 \xd37\xb6+{\x14\\Bj\xf5\xc8\xec\x8f\xbe\xc0S\xa8\x92QW\ry\xc5\xbaR\x85\xe8G\x08}\x9e6v\x9e(\xf6$\xd5\xe7r}#9\x88L;/\xc0oj\xc3\xdb\xf6j\xdb|4\xce\xf8\x11\xa3\x8e\x9eCxE9Z\xb75+\xef\xc4\xd5H\xb9S\xde9a\xcf\xd4\xb2\xdd\xf3\n\xe9\xa7\xd2\xf0\xbb\x10\x9au\xe7\'\xdb\xbd\xde\xf1\xec\x91\xba\xf0\x19Q\xe9\xa7!\xb2\xb4:\x86\xaa\x858\x91\x85\xa1\xc78\xd7\xf9\x95Nd\x9c\xf0|iD\x9c\x98\xed\xaa\x00-R\xeeG\xa6\x0b\x9f\xdb\xae\x0c;.\xf0\xe2\xf6\xdfsV\xb8Rc\x1b\x90\xe7\xea\xe2I\x8a\xeeD\xbc\x97\xb9\xfe\xe2Y\x8a+Y6\x87`n\xb7\xf4\xe6\x08\xf1\xddNl`\xb2\xe7Gi\xffp\xf1\x9bV\xafs\xbf\xd7\xe7\x84\x9b\xc3\x95S\'\xb5\x00\xa8\xd8\xd9\x1dIn\xeb\xa8\xcf\xdd\xd9\x0b\xb9{\x83b\xd8->?\x97!\xdcO\xf6\xef\x9csCD\x1f\xb2\xb2\x01\xe9o\xec\xe3\xfe\xaan\x13g\xe7\x9f\xd4\xab\xc4u\x03\x1e\xa8\x979\xf5\x93\x1d\x82\xae\x1fJ\xca\xcc\xa4\x04\xa1\xe5\x1eI\x8a\xd3\x14\xad\x02\xa7\xec\xa5\xea\x15\xc5?d\xcfm\x8fq\xc7\x97\xb6\x8f\xd7\xc0bY!\x12Uk\x8b\xb1\x04\xf2\xc0\x98\xb8=m1\xea\xc5C\x06a\xa8\xa64\x00\x0f_x\xac\x80\x82\xa5\xc5\xc5$\xce*\xc0\x9e\xf8\x82i\xd1\xa2\xa4^\x99\x16\xd4\xcbXB\xda\xc3/\x14\xfd\xc6\xd8\x88*rk\x8a\xffYWl\xa2\x1cE\xc5wd\xc5\xaak\x12\x1d+,b\xd4\xf5g\x9a\t\xa6\xad\x1f\x08~\\\x02\xfc\xb0\xaf\x11\x7f\x86\xb3\xe5\xeb\xb9\x94\xf8\xf0c[\xe0\xfe\x16\x0e\xc1\x83y\xd9?v\xb56q\xb10\xd7ts\xb1q\xb4r\xfd\x19\xd2\xfc\xcbU\xc75 .\xf8T\x07\xd7O\xbb~\xa3H!\xb9\xe7\xf5\xe6\x92#9Ml\xb0\xfe\x94U5\xbf.O\x89|j\x91G\x83\xd3U,\xc2\xf1\xe4\xae\x92w\x98>\xe8\xf1\xdcS\x9bD8N\xe3%;\xdb!!>\x11W\xcbFf5\xf1F]\x8e!\x90\xc5xr\xe1\xc1\xfa6\xbddIc*\xef\x17\xe6g\xa7\x1bwn\xfb\xd3\xd3\xb3\xb3\xa7\xaa\x1d8\x05\x8dP\xf4Z\x10\xb7\xe8#\xa8\xc6\xfbK\xb7\\m\xbfVO\x06\xe7\x983\xb5\xb8L\xdcvjf|#\xe0\x9c\xa2\xff\xa2\x87\xf9\xe7\xa2\xe6\xeaT\xf8\xfb\xf6\xab>\xcf8\xf3]\xf2\x82\xa9\xc3a\xe8\xf6vx\xb26\x9b\xab\x9b7l\xfe@A\x10,\xcd\x04\x07\x1f\xb9_R\x80\xc3\x9c\xec\xec\xcd\xbb\xc5\xec\xa36\xc9\xe9\x8fv39\xd9\x98I\xfen\xe0\x89xM\xadt\xeas\xf1u\x7f\x97\xdd9}\xd2\xf2~\xf6\x83\x9d\xb5\xe1j\xbc\xc7\xc7\x9d\xd3J\xba\x1b\xd7?\x048\tJ5:\x0e\r\xacD#\x89\x1bi8\xe3pV\x0c\xdcw\xcc7\xd5\xde6\xc4l\xf9.\xd8.\x9e^D\xdfR5\xaf}\xf3Yz\xf8\x0c}\xfcpuYu\xb2t\xe7\xcaI\xb0(\xff\x0e\x84Z\xef\x04\xf5\xc5\x0c\xa1\xb1\xea^m<\x9d\x16\x12\x9e\x9d\x03X\xc8X\xcbw\xf0\xb1\x05\xe09\x05a\xee \x97\xb1\xb0\xb1Y\xc8\xde9zp\'\x8f2fa\xec*\\\xf7\xf1Y5}\xb6\xf1\xb16\xc7m\xc2|^\x91\xf7]\xd0J\x0f/\xbb\xd2\xeeE\xcf\x16\x8a\x16\xea\x1e\x86\x0c\xdd\xd5\xe0E\xde\x82\xb2\xf7\xae\xec\x07\xce\xe2\x8a\x8e\xda\xa6V\xff\xf7\x82bbD\x94\xcb\xaa\x9a({m\x924C\xe1\xc7\xd0\x97\x89n\x9d\x12^\x96\x8c\x14\xf0\xe9\xd2`\xf827\x06\xb6]\xa5h\x04\xb9n\xc0Z\x90N\x84\x81W\x85\x8fj\xa3\x15Z6\xd2.X\xed\xa8qMa\xe3e\x14/\x83\x8e\xa5\xab\xb1"\x1c,]\xc3F\xef\x1b\xfa"\xbb\xe0\x89wl\xb2\x86\x9c\n\xee\x00\xd72\xc3u\x95|\xbd\x9eZ{\xa7\xa6P\x93\xbc\x1e\xd9\x8bC<5\'\x87(\x9e\xe2\xa2.t\xc1\x01\xfc&Ckw\x95\xd6-\xa1>z\xfb\xfc\xba\xa0F\x04l\xb8\x0fXU\xb8\rbh\xe4\x82j\xb2+\xeb\xd5$\xb2x\r\x0b\xba?\xce\x17\xe7dEq],M(\xd7y`\x98KY\x0e\xdf?o\x07\xba\x12&bu\xa5\xbb\xb9\x08\x7fm1M~\xca\xdf\xfc\xf6I6=\x9c\tv\x96\x1a\xf5=Z\xe4\x90\xf9\x0c\xdfy+\x1d\x85&\x9eud\xb0<\x079\x8cr\xfb &\x10y\xd1\x8e&Y@"C\x91\xbf\x08\xd2\xbehZ.\xd5@+E\xf4\x81OK\xe6\x94>Cb\x8f\x17\xa6\xa3\x9c;D\xbaQJ\xbb\xc2\xea\xb5t\xa5\xc1\x94\xd3dl\xc2\x1a\x8d\xf81M\xd1.\xe49;\x139\xf7\x84\xfc&\x0b\n\xf3\xedS\x1c4\x9ab\xda\xfa.\x8f\x1cw\xf8\x1c\xa6\x17d\xc4\'(\x86D=\x19\x91o8\xf7\x16\xb4Y\x1e\x1d\xe0\xf5\xd4\xbf\xa2\x84\x0b6,\xd1\xf4h\x1e\x91\xae\xfa\xa4\x97\xbf\x98\xefH\x8b\xcfe+\xb1\xeb\xed\xca\x19\xc6\xe7\xf8\xae\xa3\xeb\xea\x9d}A\x95\x15\xe1\n\x8c\xab\xc0x\x82KN\xfeN\xafP"9+`\xb6\x9as\xeel\xa4\xf0\x1dcR\xdc\xd6\xb38\x87\xd1\xfaRB~\xde\xfc\x01"`ww@G/\xba\xb9\xdc\xf7\\FEx\xcf\xb1\xa2cJ\xebf\xf5\x89L"\xbbP\x9a\x0f\x1a\xe5Eq\xc4\xc9C]\x91\xac\x9cd\xe2\\\x90\xd4ET\xec\xf8\xaf\x1f\xf2Np6\x86\x16,\xcap1\xc2\xe1\xc7M\x85\\\x974\xe8\xc3\xd2\x07k\xd8\xd1\'\x02l\x9b:;U@\xfd\x14\x9d-\r\xe4\xb2\x88*1V\xd7E~\x85\xca\xf3\xc1O+\xe8\x88\x90\xc9\xc7\x02\x15\\\x15\xb0\xe2\x1f\x89\xb7e\xb6\xf9%p\xd2\xa0\xf2\xbc)r\xaf\x1e\xff:\xb4.\xf3j3\xa6\xd6^\x89\xb2\x81\x8c\x901\xd0A\xa1z\x9e/\x11\x82r\x93\xac6H\xb5\r\xd20\xca\x08\xd5\x02\x0e\xd8\n\x1b\xad;s\xe4v\xcb\x0eeD\xa5\x08\xb8\x94L\x85\xc24\x80\xee\xday\x9b\rz\xe4\xce\xfd\xe1/\x80A\x08\x99\xcb\xd7\xdf\xd8l\xf6vZ\xa7+!\xa1\r\x9f\xf9\x18\xf4\x19\xe17]\x8cx\xad\xc2\xb3L\xd5L\xe65\n\xc2\xab}\x92\xdd\xcc\x86\xb8\xf7\x91\x85\xec\x19\x88\xa5\xc8\xc9\xc7\x04\x9e\x06\x97\xd8R\xd1;L1:k\x07M\x98\xbfD\xdc\x18^\xc1\xe5i\x99nZ\x88\xe9k\xd0T\xcc\xda\xf0\xac@@dl\x9d\xa9\x1f\x93H\xac\xec\x9ea\xb9J\xf7\x19[\x8c%j\x16\xa2\xee1n\xd2\x12\xb3,\xfb\xd4\xa6\x14\xd9<\xb8\xde\xb4\x048$\xe7p\x9d\xa7k\x7f\xa9`,e\xc1\xea\x90u\x99\xce\xce\xe3\xab\xae\xe5\xb8v \x1fki\xe8\xbf\xcc\xe5\xd5\x19\xc92\xba*@/\xc0-\xf3\xb2\x0c\xe9\xa3?\x9bi[\x8a0o\xbf\xbb+M\x11\x14\x11\xf7\x05C\x86\xa6Xnc\x8d\xbb0o\x0fm\xde(\xe8D\x17(\xb6\x1f\xa2\xa4\x1dL\x00\xdd\x17\x82\x97\xc3\xde\xf6\xa73=Fs"d\xb2\xfe\xecW\xb1!\xfaI\x1dc\x7f\xe7\xc48\n!\xd1\xd1\x16\xcb\x94\x03\xb2\xe4\xe9YA\xb3\t|\x95"A\x93K\x0bBP\x88\x0c\xadH\xa2\xc1\xf8\x0e\xe9c\xe9\xbe\xd6\xd2\xd5,\x1fJ\x97f\x15\xeb\x8a\xb9%5.\xb4\xa4\xb8\x19\xe7H\x91\xc3K\x99~$k\x02\x1al_\xf9D+\x18g\xc9\xa9\xefN\xed\x1dN\x16PE\x1b\xb5\x86*\x16\xafi\xf0\x8e\xa4\x1a\xeb\x15\'\x83a\xd0;\xce|\xf9\xe7\x05^\x01\xb2\xc1\xca\xb7\x9d\x07z\x8efu\xd8\xb7*\x06\\\xdb\xaf\xa49Z\xf0\x8e*9\xaa\xa2\r\xfc\xab\x84Z0\x87\xfaO\x04\xb3\x18\n\x9ew\t\x8a\xd1YM\x18j\xb6u^\xdd\x8f\xa5\x8f\xce\x10\xa2\xd6gl\x07r\x18{\xa9\x894\tl\x88\xde\xafG\xdc\xb83\x0f\xdf\x0f;\xd7\xe9\x8dB\xf0i\xdft\xc0\x9a\xeb\xf3].H\xa8\x07\xce\x82\x9fY\xe0|\x93\x03UT\x0eD\x0fD\x18\xf6\xebT\r\xdd\x87\xf6D{s\x04<HO\xe4&\xaf\xf2\xb1\x18\xf8\x87R\xc7G\xa1`\xd5l#\xc3H\xbeF\xdf\x04\x98\xfbib\xe0\x85\xa3\x0ec\x0b\xc3\xb6\xcc\xbei\xb0>\xc4\x93@\x00\xba\xd7\x9a\xb9\xa1\xc5E\xc6\xac\x8eH\x03\xecJH\x89_\xd8\xd6\x9cj7\xf0\xedEg!wv\xa9v\x8e\xc2\x1e\xe3\xe1\x83\xc5\x8b\xdaU!]\xa1\x1e\xd4\xaa\xea\x08\xdf\n\xd1\xea.\xfa\xcaC\x0b\x98vR\xc6Q\xe1+\xae\xd8\xea\xf2(\n\xa5\xc8y\x17\xfd\xe2\xf1[:x\x8d\x15iU,\xba \xfdO\x1c\x025h\xc2\xb1\xdfLi\xdb\xd8u\xa4\t\xbep|\xedf\xe7r\xa58\xcet\x13\xc4x\xb3\xb7}w\xd7sy\x83\x81\xf3\x8d\x98\xea\xe4\xf1\x8f\xda\xf7\x9f\xad\xfd\xb7^\xa3pH\x03\xc7\x13\x94\xf9Xf1G\xf9\x11\xf9\xc6\xa7\xf4\xf5;[}}2\x96-h&\xb9\xb8x\x0b\x8f\xb2\xeal\xd2\xbaG\x911\xac\x14n>\xbd_Q\x9c\xaf\xa8\x94\x9a\xba;\xe9\xf8\xe2\xa2\x9a\xecJ \x14v\xdca\x97\xdf\x82Z\xce\\\xd3-\xd1\x12\xe1D\xbe\xcc:s\xe6\x8c\x8a\xaf\rWkw\xae\x9c\xa6\xdc\x0b\xb3\xe2\xcdK\xa0\xea\x1c# \x1e\xa3^m\xa27\xb27\xccCA <P\x93K\xd9\xa6\xc3\x11\x0b\xd5\x8ay\x06\x04\xeb\x9b/\xfe\xc0\x99\xca~1oi\x03\x03\x0b\xde\x92\xff,\xba\x8a\xf3\x1f}\xf8P\xe1\xe0\x14\x88\xfeVt\xb1\xfe\xb7\xe8\xba\x81\xec-\xfe\xa9\xb6\xc5Iu\x8e\xbd4\xb8a\x97b\xc8\xa6N\xce\xbcZ\x1a\xa1\xc3\xea\xac/\xf6\x8b\x9e\xeb\x98N\x00\xd9(\x88\x12\x86Nf\x89cf\x8b4\xc3U=/]\xef\x07\xb7\xf8>\xc4.$`|\xcf\xa3\\p\x83\xbec\x81\xb7\xcf\x9eY\x9a\xbf\xb8m\xf5_\x9b\xc9\xf1\xda\xa4UE\xc1\x16\x95`\x18\x0e\xc8/\x01\xc7\xf4\xf2\x99\xe5\x1ft\x8f\xd4\xba \x1a?\xb5\xc9i\xe1-\x99\xf1\xe4\xc0\xa4*\x02,\x9bc\xadj\xcd\xe37<\xa7\'\xa4\x98\xf4p2\xa3\x89\x156\xab\xb4\x91\xcd\xd8\xac\xea\xcd\xaa/\x91\xc5\x15\xf1M\x8c\xe6W\x18.,n\x1e \xdd\x8f\x94C\xa6/\xcbtl\x08\x9b\x91:\xf0N\x94{\xdb\x91\x0b\x9a\xb1\xe5#\x04%\x87\x82f\x8a\'m\xdd\xc4\xa2+\xd7x\xc3\x13\x94W\xd2\xdf\xd2\x02\x1b\xd1\x82px\xe5>\xb7\xaa!\xbf:\xdf\xe6\x97P\x99\xa6%\x18[\xbb|\xd6\x92t\xf7e~\xf4`\x82\'\xdc\xedl\x18\x94\x9a\xe6|\x7fG\x87\xee\x98\x17;\xbc\xe9\xbe\xb8O\xb2\xdeun\x123Q"c\xb3,\x94\xc2D_\x13\xc7\xa8\xb0\x84\x12#\xb43\x0fn|\xbfd\xa64\x82\xbd\xa1u\xf7\x83A\xfc>\xb3$0\xad\xd1X1\xf1\xea\xb2\xb1\xe7\xeeIZ\xcc\xb1\xd3]\x8ce\xcb\x07\x15\xdf\x7fZ\x9er\x9e\x97\x12\xd2\x0f\x1d\\\xc1_\xfbg\x9c\x7f\xb1\xef\xe9\xe4bg\xea\xe4d\xf7\x93\xff\xd88Q\xa7\x87\x06.\xec\xf2\x0e\xf0\xc9\xc3YJc^\xee\xf5Ku\xc6\xb4\x99@\x0fq\x18F]\xc4\xf1\xc7#\x04\xf1\xf7\xaa\xea+e\x9a\xa5\xb3\x15>\x1b\xf1.\xae\r9\xad\xb8\xa8\xdb9A\xbe\x19\x814:>\x0ek\n\xdd\x83[\xeeg\x98Y\x87\xf9\x1d\xdeb\xd4P\xf1\xe8\x10H^^l\xdd\xe3"Lw%\xa2\xde\x99\xcb\x9d\x99\xd23{\x1e\xa6afRo\xa6\xb9|\xc6\xa8\xe6\xe4\n\x0e\x9f$\xa2\xd8`\x1f\xa9\xee\xfb\xe1\xcf*f\xb6+\xd7\xd7\xa3I\xd1\x97\xb8%\xd8fd\xe4\xba\xb3\xa8e~i\xd0\x86)\x12V\xff\xe1\x05\x00\xd9\x11B`\xe5\xc8\xd6\x17\x9b\x8fd~\xdd\x92\x80\xca\xc2\xb6)\xf8x@}`2\x9f\xf3\x9a\x88\xc1\xd6TR\x10\xb8\xb4?\xad.\x92\xa6\x95[\x17\xfe\xf4\x82>\x02o\x991\x03\x87\xd6\xb5W\x8f\xed\xca\xee\xe5$fE\x9d\xfb\xbb\xa4\xd9\xd6\xc3\x7fr\x94\x18\x14\xc8r\xf0\xc0A\xe2_\'0\xb2\x7f\xb1\xf4\xaf!\xecW\xae\xfe\x19\xc8\xa0I\xdd\xb6\x0f\x03\x99\xc4\xe9\x15\xa0\xf0\x06\xc6@i\x11#\x08M\x91\xac1\xb8\x84\x1f\xd0\x80M\xf5\x01\x93 M\xfe\xe2NSU\x81\xb1\'\xea\x1e\x8f\x92*K\xad\xb6\xbd\xdd\xb3\xe5\xce\xa2\xfa\x82=\x01#\x1dp\x81\x13\xdf=\x9c\xa1Ao\xd6g\xd7\x11+39*Z\x04\x0f\xd3\'j)\x11\xa2\xf9w^\x06\xc6\xf2\x88(\x0e\x0f\xc0\x8a\x84.\xe1\r\x0e\xddr\x99(5\x15\xa1\x98+G\xee\xf1\xf5lQ\xc5EJ(\xfc\x19\xb8|\x95K\x8d\x00\xeb\xd94\x1a\x8f\xd2\x00\xff\xee\x9bjr\xccj\xa8\x90\xf2G\x18\x8e\x1e\x83\x9e\xca\x92\xd83Eb\x18\xd2\xc2\x9c\x99\x167\xfb~$\xe0\\\xe7\xeda\x89\xd8\x19?\xacx\xc8\xca\xaf\xdf\xf8\xb5R\xf0\x135\x9f\xe6\x883=X\xc5\xc5\x99!k\x8a\x8e\xef\xc9\xfdr\xe9\xd3\x9b9\x97o8YG\x94?9\xea\xb0a\x8f^{`\xa0\xeb\xaf\x99D\xf2\xefLr\xb5\xb6\xb0ps}\xfc\xcf\x85\xe7\x9f\x94J\xd7s\xcd\xe2\xc6\r\xfdp\xc3N\xb2a\x87+\xaf\xff\xb4\x99\x0fK\xd0c\xa5\xe4\xf8\xe2\x9b\xaa\xfd\xb2\xa5i0\xea\\\xab\xf8\xfb\x9e\xd7&\x9e\x84\xfc`\xbe/\xe8\xaf\'\x14Mqr7~\x08Qe[-7Z\x18\x8c\xeb\x03\xcf\x0c\x9ei\x7f\xf2\xd6\xd4\x86d\xdc|\x19\\_\xed\x83f\xbc\xcf\xc8\xfd\xb4W\xbe\xaeTN!\xdaikubX>+<i\xb7\xe8\x03\xe2XQ\x00\'\xa52\xad\xb6\x0b\x11)\x1a\x01\x85kD\x05\xea\x97\xf4\x1d\x9fRut]\xd2\x9f\xbeLI\x15~\xeb8RX\xd9\x8e\xfa4vmb\xedr\xec\xeb\xde\xech\x97Q\xb1H\xcbf\xcb\xac\xe8e]\xf5\xdb\xf6\xe8\x9b\xf1\xb1\xf9s\xad\xb3\xef\x06T;\xba\n\xe0\xaa\xcc\x0f\xf5\x90U>\xc7\xf7\x10\xf9\xab\x15A\xf26N?\xea\xb9\x96\xeb\x8e\xa4]\xc7\x9aF\xa5|\x87;\x1fs\xc32S1\x87\xc3\x86Y\xeb\x82\xf9*\x08\xb5nr\xe1\xb3\xe6\xebk\xd0\x89\x1a\xd4\xea6\xe2k\xea\xba\xd4\x00\xf7(\r\x06\xf7(-\x06\x8f\x9e\xc4\x00\x0f$X\xd9\xb89\x84\xa3\xc7\x1e\xf9U\xcc\xb2\xa89\xba%5\x8d\x12\xcfMDGr\x8f\xafT\x82\xd6\x1e\xbc\xe4\xf3\xccI\xb4\xa4\x15_Ig\x96\xb8R\xe2*\xa3\xb6<\xa3\xb6M\xdevoR\xd1|;\xe2\xae6y\x1e>4\xa1\xe9\xb7z\xfb\x061\x1a\x0c\xbcG\xb2a\xc6^\xc6\x11\x98\xf9\xf2\xf5\xefHC\xb2\x1dy\x04k\x9c"0\x1d\x88\xd2\x9ca\x11\x95\xdd\x00\xc9\xf39\x1f\xa4g\x1d_6\x84Q\xd9\xa4z\x85\xc37\x86\xab\xc7ivdL\'\xaa6\xda\xe6\x85[@\xfb\xc0S\xdc\xa8M\xf7\xd3\x82K\xae\x00\x80\xa3\x17\xf1\x94\xb0P\xea\x83\x9b\x0e:\x17\x93\xaf\\\x95\x1b\xa1\xe3\x90Z\x10q\xcdc\xd4s\xaa\xaf\x1b\xf4yR$\x1b\xf4\x1fs:\xdcy\xd1\x84\x84\x9a@\xe6\xa2\xe9f\x04\x911>\x89<$T\xa4tf\xdf=\x98\xb9\x83\x13\x925\xb3\x06\x17\x90\x83\xe6\xbc(9\xb6\xfa\xf0^]\xbd\xb0\xd7\xa3A\xeb\x1fB`\x84^"\x95E`\x9d\xa2_\xa8\xaeR\x85dg\xaf\x88\xd4q\xa9\xf3\xc2(#\x95}\x12YIrI\xe84Y\x92\xb4\xe8\x1f\xf0\xdb\xa9\xa5\xda\x89\x07\xf7\x11\xe6w\xb8\xd4\xbe\xce\xd2\xb6C\x1d\xb0\nU\x97=^\x19!!\x0c\xa1\xcc\x955E4\xf2\x9aE\xc6\xccU\xc1\xe3\xf4\x99\xf5\x10\xf7\xc8D\xba\x00\xcc~c\x15\xac\xf2\x16\xccPF\xd5\x8a\x00\xd3x\xb5\x8a\xae\xa3\x17\xc6\xdf\xd8\xf2\x96\xfa\xac\t\xd3\x9b\x00\xf2:"\xcfCi\xe3\xb9\t\xb0\xc6dz\x8c\x0f\xd1\xac\x19$\xb5\xa6\x94{\x8e\xf2\x91L\xc4\xda\x1d\xc2_\xf6\xa8Kq\x07\xa3\x07\xe7\x88\xe5\r#i\x98\x14\x19\xd9]\xbf\xa4\x11\xa9v\x8f\xc0\xc3tw\xe3\x93\xe7^\xca@\xccd\xc0%\xe4W\xe4\xb6\xd3}I\xc3!\xd7\x84\xed\xf06\x1f\xdb\x1e\xe8\x87"l#!,^\x10\xd4\xecgy|\x82\x112\xf8p#3?\xce\x06h\x8b\x92\xf5ZBX\xe0\xe1\x86-\xff%{\xe9\x02\x19^\x9a\xf5\x89\xfc\x94f\xb4\xb5\x94\x1ag\xc1\x81<a\x18E\x97\xb1\x92\xa5\xe5#\xe3\xda\xa60~\x00\r\x1b\x9d-_\xf3jL\x15\x10/\xb6LEf\xd0PUz\xd4\xaa\xecI\x96\xca\xdb\xee\x01*2jH\x02`\xe5[\x06\xf4\x94\xde\xdeQ\x19\xc77\xe7mT\x8e/K\xa6\xc1\xab\xa6\t\xb3*-pv\xdb\x1d\xc3\x82\xb0\x8f\xde\xa2"p=\xd5\x0f|dQw\xf0\x18\xdb\xa5\x82\xabP\xbf\x14tu\xf4\xfe\x87\xf6\xd7\x03o\xa7\xcb\x1a\xc9\xfb\x96\x81\x1f\x8f\x7fj\xd9X"\x85$\x0c\x11\x0e\x0e\x1d\xef\xff\xa1e\xde\x7fiY)>\x8b\x9b \xf4\xf2\x960\x02\x8c\x08\x04\xc6\xb3\r\x97!\xaa\xf0:\x94V\xbdk\xf6azM\x95\x89D\x97\x97|\xf7#I\x19\xe9\x12\xafr\x19\x19<\x90\xbd\x1d\rV#\xf9p+|\x94C\xac9\x0f\xa9Oo5\xdd\x81\xc4\xb1\xa6\xed\xda\xea\xd83\x9d\x9c\x1a5\\\xd6\xf9<\x01?\x11K\x9dw\x85\n\x94\xbc^9\x93\x15}\xdd\xa2\xe2\xfac\x13\xf4\xd5\xc5\x0e\x1b$\xca\x16_b=\xdc^\x89\r\x9a5\xd4&\xaf\x11\xd3f22p|z$zp\x93\xef9\xe4\x19*LY\xe3\x81\xaa\x99M\xfdQ\xcbR\xf4\xb58`1+\xee1\xe2\xfd\xd1X9\xca\xfb\x9c/\xaeoG\xce\xaf|\xcfj3[\xef@e\x83\x03\x13\\\x93\xb7\x1aB\xec\r\x13\xf7\'YowmL<\xb2\x1cfug\xe8\xdfg\x89\x8ff\xf9>\xad\x1eI\xd6l*J\xad\x17\xb9\xb7F\x16<\x1ej\x87\xfae\\\x9b\x9d\x16\x83\xfb\xceGNh\xf1\xd3\x8b\x13\x14\xc6x\x87\x10\xc6\xc4$K\xb8\xb3$Kx\xb2\xa4\x89L\x9b\x038z\x8e\xe0\xebI\x1a&\x13\x18\xd3\xc1\x92\x1b\xc3=\xbe\xb2\t\x95c\xf4A\xe66\x9d\xb4\xf2\x0b{\xc2A\xb70/\x87\xe9\xf6\x91\xe1j\x97s\xdev/J\xd1\x82\xa6dg\xae\xfat\xd6\x90\xa8\x8f\x93\x95_&\xc2X\x1e\x91\xba\xd1!r\xeb\xf3&\xc2\xfbj\x0c=/\xc6e\xbb\x8e\xea\x06\x81\x99xk_\xa5\xf7FJ?\x0fF\x0e\xda)\xc7A\xc3\xf6\xd2\xc9\xf1D\xd6B\x1a\x83\x04mDF\x11H\xc9\x1a\x97Tn\xa4>p\t\xd2y\xd0\xaf-h\x15r\xd2a\x97\'\xc5sJ\xe6\xcd\\*\x01\xc8\xa7\xe3\x9e\xd5>]94X\xed\xb0\xcb\xf2\x04C(\x86|\x96@8\x81\x80\xf1\x8epg\xb3$M\xe6P\xf5D\x83\xac\xd0\x85X!\x99\xc4\xa12|\xd2\xc0-Z|\xd2n\x84\xe9YD)\xd9\t\x18G=\x11\xdas\x0f\x8a\xb1\xad>\xda\xf2\x1ft\xf5\x84hR\xa2\xeay\xad_\xa8\x10\t\xf1\xbeP\xf5N\xc8=\xa87\xea"\x93\xa3\x99\x88\x85\xeas\x9c\x0cS\xce\x10\x12f|\xc6\x10RT\x113sH\x14?\x94\xa3.Jy\x83\xee\xf9w\xb0\xef\xe7n,\xf4dP\xff"qd\x07;kA\xd4Q(\xa6\xca\xb8\x11c\xc8\xf2\xd9\xd3g\xae\r\xebq\xac\xe0\xacZ.\xd1Z4\x1ai\xf4\xd6\x12\xe5C\xa8D K\xc1\x83z\xd5\x94\x1d\x00\x10\x95\x94h\xa4\xa6\xc8\xa4\xc4<\xe0tp\xb8\xfd\xb7@\xe9\xbc\x8dI\xfa\xf0\x80:\xba\x88r\x15y\x01\xf6\xe6Fb\xbd\x15\x1dI\xdd\x87wt\xac\x9b,b\xc5\x143Y`\x0f\xf2$?B(\x99w\x17\xfdH4\xe5\x92CO\x16\xfd\xdb\x15\xcc\xca~lGj\xc0\x92%\xb5!\xd2\x08\x9eH\'Z:*\x83\x03^\x84\xed[\xa2\xd5L\rK\xb4\x8an\xe92\x1cr\x84\xaf`\xaa\'HG\x1f\x92r\xa4\xca\xbe\xf2U-(\xf3\xe0KK\xa2\xda\x1d\xf7\x06J\x803\x07\x11\xe1\xe9\x03\xcc\xad\x90\x8b2\x99<M\xd4\xd0LY\xd2\x8d\xab\xc0r\xb8\xb5\x06\x18\xb9\x8f\x90\xec!I\x0e^s)\xcb\xfe}C\xd5\x02\xde\xc9\x0b\x9d\xa5\x18s\xbe \x1d\xe22\xd7\x1b-\xf6\xa2L\x14G\xfe\xcb\xd8^V\xaa)\xef\xf5&\xe7\x13\xf5Y\x83hkeO\xce\x82\xe1.\xb6\x8b|\xc9\xbc\x93\t\xb3\xe0\x80i\x1a\xe3\xfb\x03\xday~?\x80\x8f\x8bD\xba\xce\x18"5m\xdc\xd5\x80\xc8\xde\xbc\xa5\xce\xdc\x84\xe62\xff\xae\t\xec\xba\xb0l]\xf1S\xbd\xbd\xb2{\xa7m|E\xd5\xb0\xcez\xffFe\xd6(\xcbb\xb9\xe1{G}\xbf\'\xbbg\xde\xa7W\xdb\xf2\x97\xe5\x96\xd7\xd4?\x15\xdem\t|\x9d\xfd\xa0\xf0\xf5\x7f\x14\x0e\x8f@\x00\xf7o\x8d\xff\xbao\xc6\x83\xfb\xf3\xf8\x8f=\xfd\x9f\xf0_W\xb2\x18\xbfAe\xe0\x7f[Q\xff\t\xfcu\x9b\x88\xff\x1b\xd0\x18\xe1\xff\xdc\xdf\xfe\xe9\xe0\xd7\xfd\x1d\xeeo\x0e6\x10\xffs\x05\xf9\'\xfa\xd7A\x84\xe07t\x15\xd2\xff\xbd\xf1\xfb\xd3\xc3\xaf\xcd4\xd6o\x1e\xe80\xff\x18_\xfe\x84\xfe\xdaa\xe2\xfc\x06\xcd\xc3\xfa\x8f\xde\xfbO\xf0\xaf\xad\x17\xd9o\xe0\x01\xec\xbf\xb5\xa4\x7f\xfa\xf9\xf5o\x9f\xe47?\x878\xff\xbdm\xfb\xd3\xcb\xaf\xa9\xf5\xbb\x97f\xfc\xff^0\xd4\x95\x90Q~>\x03xx\x85>\xc4\x91N\xfc\xf3\xdb\xff\x00PK\x07\x08m\n\n<"\x17\x00\x003\x1a\x00\x00PK\x03\x04\x14\x00\x08\x00\x08\x00\x8aV\x93[\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00H\x00 \x00argrew/C_ANNOTATIONS/D1_to_D2/Annotation_2018argrewrite_102_NEW.txt.xlsxux\x0b\x00\x01\x04\x00\x00\x00\x00\x04\x00\x00\x00\x00UT\r\x00\x07\x0c\xe1DiD)Ii9lGi\x9d\x99uTT\xed\xfa\xf7\x87Fr\xa4F\x1a\xa4A\x1a\t\xa5\x95N\x01\x01\x81\xa1\xbb\x19r\xe8\x90\xee\x90n\x86n\x90\x06\x01A\xe9\x01I\x87n\xa4SP@x\xd1\xe7\xacs|<\xbf\xf3\xfc\xf1\xeeY\xf7\xc4^\xf7u\xad\xb9\xbf\xeb\xde\x9f}}\xf7\xa5\xaa\x80\x82J\x04\xc0\xc4\xc4\x04$\xf9\xf2+\x03~;\xee\xdf\rS\x07\x13U\x88\x83\xa33\xa7\x89\x03\xc4\x8c\xc3\xc3\xce\xb62^I\xa1\x97\x8bH\xea\xe2\x071\xed\x15?\xb5\xd4\xa717\xa0\x99\xb8*\x85\xe3s\'\xd0\xb8\x85\xae\xad\xa8l>\xe5mG\x1a\\\xfb\x85^\xabw\xcb\x16\x15\x15\xe7\x94u\xb1\xcc\x19\x9e(\xce\xf4d*1\x11\x1d\xd7`c\xd0\xb6\xf5u\rx\xcb\xc2c\xca\xf4UaEht\x13\x9e7\x05M\xee$O\xdeG\x9f(e \x81\x06\xbeN\xc8\xc3\x0f\x8c\x0c\x9c\xd36\xa4\x13_\x9e\xae\xc2<\xdfP\x02\x95\xb7Y>\x01\xcd\xd8\n\xe8\xbdt\x0fH(E\xbf\xbd\x86\xdcV\xd9N\xe5\xbb8\xf8f\xa2U>\xe4\nD\'D1B\xa3[\xb2E\xad\xee\xc9\t\x16z\xd5\x0f~@b\x9d^d\xccj\xc1a\xd7\xdb?\xb1?\xf2\xa3\xdd[4\x15X\xf8\xc2?\x03\'o\xc7\x124\x18\x145\x96\xbf\x0e<\xee\x91\x88\xeeL\xe8;9\xb1n\xfb\x88[\xbc\'\\\xfch\xcb{\xa8Tp%\xffQ\x0e\xdbI\xb9\x9f\x0b\x95\xf4nF\xa4K2\xd5\xd8\xe6\x81g,\xc7\xe8+)__p\xa2\x0f\xb2\xaa\x02\x06f\x06]\xfc8*\x12\x00pv7T\xff\xa7\x84\xd8w\xc3\x00bf\xeb\xcc\xc9\xf1\xf3\xbd2\xa1[\xb9\x87\x0b\'\xe4\xd0\'\x82\xf9bj!\x0e(\xa9\xe4.!\xdb\xa6d),.;\xcfoM(\x13\x8e\xb1\xb1\x7f\x0f\x03\xf5\x19\x8e\xdb\xf2\x83\xad\x8b-\x95\xba\xb9\xfdU\x8b\xe3(\x96\xa7X\xf2U\xbb\xd2X8!\x15\xd8A\t\xb1\xa1WS\xd1\xf3n/\xa7D\x97+ZLO\xbe\x18\x93\x14\xb2\x982\xc8lz`\xc7\x8d\x84\xe9o\xa5?\x0c9\x99P?I\x1f\xe2\xc5\x056\xa4\x9d\xf9\xd7X\xa5\xdb\xc8\x1a\x90\xd6\x95\xbf\x16\xec\x8e\xc8z\xc9\xb3\xbf\xa7\x13\xd1c\xd3\xabp4y\x01_\xa6L+\xe8\xeb\x12S\xfc\x9e\xccl\x9a\x85n\xca\x90B\xaa\xcf\xac\xa4\xf2\\\x1d\x9cK\x00\xdf\xb1\xbdQ\xc7\x00}4\xfcTe\xcc\xfa#\x9crS\x85I

In [64]:
!unzip -q argrew.zip -d /content/
!echo "---- ROOT ----"
!ls /content
!echo "---- ARGREW ----"
!ls /content/argrew

replace /content/argrew/C_ANNOTATIONS/D1_to_D2/Annotation_2018argrewrite_100_NEW.txt.xlsx? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
---- ROOT ----
 argrew  'argrew (1).zip'   argrew.zip	 phase2_output	 sample_data
---- ARGREW ----
C_ANNOTATIONS  essays  revision

In [15]:
from pathlib import Path

ARG = Path("/content/argrew")

assert ARG.exists(), "ARG root missing"
assert (ARG / "essays").exists(), "essays missing"
assert (ARG / "C_ANNOTATIONS").exists(), "C_ANNOTATIONS missing"
assert (ARG / "revision").exists(), "revision missing"

print("ARG root OK")

ARG root OK

In [16]:
D1 = ARG / "essays/C_DRAFT1"
D2 = ARG / "essays/C_DRAFT2"
D3 = ARG / "essays/C_DRAFT3"

A12 = ARG / "C_ANNOTATIONS/D1_to_D2"
A23 = ARG / "C_ANNOTATIONS/D2_to_D3"

R12 = ARG / "revision/ConfirmLogRev12"
R23 = ARG / "revision/ConfirmLogRev23"

for name, p in {
    "D1": D1, "D2": D2, "D3": D3,
    "A12": A12, "A23": A23,
    "R12": R12, "R23": R23
}.items():
    print(name, "exists:", p.exists())

D1 exists: True
D2 exists: True
D3 exists: True
A12 exists: True
A23 exists: True
R12 exists: True
R23 exists: True

In [17]:
print("D1 sample:")
!ls /content/argrew/essays/C_DRAFT1 | head -n 10

print("\nD3 sample:")
!ls /content/argrew/essays/C_DRAFT3 | head -n 10

print("\nAnnotations D1→D2:")
!ls /content/argrew/C_ANNOTATIONS/D1_to_D2 | head -n 10

print("\nConfirmLogRev12:")
!ls /content/argrew/revision/ConfirmLogRev12 | head -n 10

D1 sample:
draft1_2018argrewrite_100.txt
draft1_2018argrewrite_102.txt
draft1_2018argrewrite_10.txt
draft1_2018argrewrite_14.txt
draft1_2018argrewrite_15.txt
draft1_2018argrewrite_16.txt
draft1_2018argrewrite_20.txt
draft1_2018argrewrite_23.txt
draft1_2018argrewrite_24.txt
draft1_2018argrewrite_38.txt

D3 sample:
2018argrewrite_100.txt
2018argrewrite_102.txt
2018argrewrite_10.txt
2018argrewrite_14.txt
2018argrewrite_15.txt
2018argrewrite_16.txt
2018argrewrite_20.txt
2018argrewrite_23.txt
2018argrewrite_24.txt
2018argrewrite_38.txt

Annotations D1→D2:
Annotation_2018argrewrite_100_NEW.txt.xlsx
Annotation_2018argrewrite_102_NEW.txt.xlsx
Annotation_2018argrewrite_10_NEW.txt.xlsx
Annotation_2018argrewrite_14_NEW.txt.xlsx
Annotation_2018argrewrite_15_NEW_NEW.txt.xlsx
Annotation_2018argrewrite_16_NEW.txt.xlsx
Annotation_2018argrewrite_20_NEW.txt.xlsx
Annotation_2018argrewrite_23_NEW.txt.xlsx
Annotation_2018argrewrite_24_NEW.txt.xlsx
Annotation_2018argrewrite_38_NEW.txt.xlsx

ConfirmLogRev12:
rev_100.txt
rev_102.txt
rev_10.txt
rev_14.txt
rev_15.txt
rev_16.txt
rev_20.txt
rev_23.txt
rev_24.txt
rev_38.txt

In [18]:
def find_draft(folder: Path, prefix: str, eid: int):
    matches = list(folder.glob(f"{prefix}_{eid}*"))
    if not matches:
        print(f"[MISS] Draft {prefix}_{eid}")
        return None
    return matches[0]

def find_confirmlog(folder: Path, prefix: str, eid: int):
    matches = list(folder.glob(f"{prefix}_{eid}*"))
    if not matches:
        print(f"[MISS] ConfirmLog {prefix}_{eid}")
        return None
    return matches[0]

def find_annotation_xlsx(folder: Path, eid: int):
    matches = list(folder.glob(f"Annotation_2018argrewrite_{eid}*.xlsx"))
    if not matches:
        print(f"[MISS] Annotation {eid}")
        return None
    # choose most revised version
    return sorted(matches, key=lambda p: len(p.name))[-1]

In [19]:
import pandas as pd

SEMANTIC = {
    "Claims/Ideas",
    "Evidence",
    "Warrant/Reasoning/Backing",
    "Rebuttal/Reservation"
}

def transition_is_nonsemantic(annotation_xlsx: Path, confirmlog_txt: Path):
    # revision must be verified
    if confirmlog_txt.read_text().strip() == "":
        return False

    df = pd.read_excel(annotation_xlsx)

    # DEBUG
    print(f"[INFO] Reading {annotation_xlsx.name}")
    print("Columns:", df.columns.tolist())

    # find revision type column (dataset-dependent)
    possible_cols = [c for c in df.columns if "Type" in c or "Revision" in c]

    if not possible_cols:
        print("[WARN] No revision-type column found — conservative reject")
        return False

    for col in possible_cols:
        for val in df[col].dropna().astype(str):
            if val in SEMANTIC:
                return False

    return True

In [20]:
def discover_valid_essay_ids():
    ids = []

    for p in D1.iterdir():
        if not p.name.startswith("draft1_2018argrewrite_"):
            continue

        try:
            eid = int(p.stem.split("_")[-1])
        except ValueError:
            continue

        d1 = find_draft(D1, "draft1_2018argrewrite", eid)
        d2 = find_draft(D2, "draft2_2018argrewrite", eid)
        d3 = find_draft(D3, "2018argrewrite", eid)

        a12 = find_annotation_xlsx(A12, eid)
        a23 = find_annotation_xlsx(A23, eid)

        r12 = find_confirmlog(R12, "rev", eid)
        r23 = find_confirmlog(R23, "rev_23", eid)

        if all([d1, d2, d3, a12, a23, r12, r23]):
            ids.append(eid)

    return sorted(ids)

ESSAY_IDS = discover_valid_essay_ids()
len(ESSAY_IDS), ESSAY_IDS

(21,
 [5,
  10,
  14,
  15,
  16,
  20,
  23,
  24,
  38,
  42,
  46,
  50,
  54,
  62,
  66,
  70,
  74,
  78,
  82,
  100,
  102])

In [81]:
from google.colab import files
files.upload()

Saving ai_baseline.txt to ai_baseline.txt

{'ai_baseline.txt': b'Self-driving cars have emerged as one of the most discussed technological developments of the modern era. Supporters argue that autonomous vehicles have the potential to transform transportation by improving safety, efficiency, and accessibility. Critics, however, raise concerns regarding reliability, ethics, and the broader societal impact of removing human drivers from the road. Evaluating both perspectives is necessary to understand whether self-driving cars represent progress or risk.\r\n\r\nOne of the strongest arguments in favor of self-driving cars is their potential to reduce traffic accidents. Human error is responsible for the majority of road accidents, often caused by distraction, fatigue, or impaired driving. Autonomous vehicles, in contrast, rely on sensors, cameras, and algorithms that do not suffer from these limitations. If properly designed and tested, self-driving systems could respond faster than humans and consistently follow traffic laws, leading to safer roads overall.\r\n\r\nAnother advantage is increased efficiency in transportation. Self-driving cars could optimize routes, reduce traffic congestion, and improve fuel efficiency through coordinated driving behavior. In addition, autonomous vehicles could offer mobility to individuals who are unable to drive, such as the elderly or people with disabilities. This increased accessibility could improve independence and quality of life for many members of society.\r\n\r\nDespite these benefits, there are significant concerns surrounding self-driving technology. One major issue is reliability in unpredictable environments. While autonomous systems perform well under controlled conditions, they may struggle with unusual scenarios such as extreme weather, unexpected road hazards, or complex human behavior. A single system failure could result in serious accidents, raising questions about whether the technology is mature enough for widespread use.\r\n\r\nEthical and legal challenges also complicate the adoption of self-driving cars. In the event of an accident, it is unclear who should be held responsible: the manufacturer, the software developer, or the vehicle owner. Additionally, ethical dilemmas arise when autonomous systems must make decisions that involve potential harm. Resolving these questions requires careful consideration and clear regulatory frameworks.\r\n\r\nIn conclusion, self-driving cars offer promising advantages in safety, efficiency, and accessibility, but they also present unresolved technical, ethical, and legal challenges. While the technology has the potential to significantly improve transportation, cautious development and regulation are necessary to ensure that its benefits outweigh its risks.\r\n'}

In [7]:
from pathlib import Path

def load_text(path: Path):
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        return f.read().strip()

In [8]:
AI_TEXT = load_text(Path("/content/ai_baseline.txt"))
AI_SCORE = sbert_score(AI_TEXT)

print("AI baseline SBERT score:", AI_SCORE)
print("AI essay length (chars):", len(AI_TEXT))

AI baseline SBERT score: 0.03659766302934076
AI essay length (chars): 2703

In [9]:
!ls /content/argrew

C_ANNOTATIONS  essays  revision

In [23]:
rows = []

for eid in ESSAY_IDS:
    # --- Drafts (TEXT) ---
    d1 = load_text(D1 / f"draft1_2018argrewrite_{eid}.txt")
    d2 = load_text(D2 / f"draft2_2018argrewrite_{eid}.txt")
    d3 = load_text(D3 / f"2018argrewrite_{eid}.txt")

    # --- Annotations & verification (PATHS, not text) ---
    ann12_path = find_annotation_xlsx(A12, eid)
    ann23_path = find_annotation_xlsx(A23, eid)

    rev12_path = find_confirmlog(R12, "rev", eid)
    rev23_path = find_confirmlog(R23, "rev_23", eid)

    # --- Semantic filtering ---
    valid12 = transition_is_nonsemantic(ann12_path, rev12_path)
    valid23 = transition_is_nonsemantic(ann23_path, rev23_path)

    # --- Detector scores ---
    s1 = sbert_score(d1)
    s2 = sbert_score(d2)
    s3 = sbert_score(d3)

    rows.append({
        "essay_id": eid,
        "AI": AI_SCORE,
        "D1": s1,
        "D2": s2,
        "D3": s3,
        "valid_12": valid12,
        "valid_23": valid23,
        "Δ_AI_D1": s1 - AI_SCORE,
        "Δ_AI_D3": s3 - AI_SCORE,
        "Δ_12": s2 - s1 if valid12 else np.nan,
        "Δ_23": s3 - s2 if valid23 else np.nan,
        "Δ_13": s3 - s1
    })

phase3_df = pd.DataFrame(rows)
phase3_df.head()

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_54_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_54_NEW_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_102_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_102_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_14_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_14_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_15_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_15_NEW_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_16_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_16_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_20_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_20_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_23_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_23_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_24_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_24_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_38_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_38_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_42_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_42_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_46_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_46_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_50_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_50_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_54_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_54_NEW_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_62_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_62_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_66_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_66_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_70_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_70_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_74_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_74_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_78_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_78_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_82_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_82_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_100_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_100_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

[INFO] Reading Annotation_2018argrewrite_102_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']
[INFO] Reading Annotation_2018argrewrite_102_NEW_NEW.txt.xlsx
Columns: ['Sentence Index', 'Sentence Content', 'Aligned Index', 'Identical?', 'Original Paragraph No', 'New Paragraph No', 'Revision Purpose Level 0', 'Revision Operation Level 0', 'Revision Index Level 0', 'Revision Purpose Level 1', 'Revision Operation Level 1', 'Revision Index Level 1', 'Revision Purpose Level 2', 'Revision Operation Level 2', 'Revision Index Level 2']

,essay_id,AI,D1,D2,D3,valid_12,valid_23,Δ_AI_D1,Δ_AI_D3,Δ_12,Δ_23,Δ_13
0,5,0.036598,0.044164,0.038704,0.060779,False,True,0.007566,0.024181,NaN,0.022075,0.016615
1,10,0.036598,0.495872,0.498623,0.191307,False,True,0.459275,0.154710,NaN,-0.307316,-0.304565
2,14,0.036598,0.624233,0.385327,0.435338,False,False,0.587636,0.398740,NaN,NaN,-0.188895
3,15,0.036598,0.521351,0.234682,0.225352,False,True,0.484754,0.188754,NaN,-0.009330,-0.296000
4,16,0.036598,0.415750,0.406901,0.322310,True,False,0.379152,0.285712,-0.008849,NaN,-0.093440

In [24]:
# Cell: sanity diagnostics
import numpy as np

df = phase3_df.copy()

# Basic stats
print("N essays:", len(df))
print("AI baseline score (fixed):", df['AI'].iloc[0])
print("Human D1 mean:", df['D1'].mean(), "std:", df['D1'].std())
print("Human D2 mean:", df['D2'].mean(), "std:", df['D2'].std())
print("Human D3 mean:", df['D3'].mean(), "std:", df['D3'].std())

# Percent of human drafts scoring higher than AI
pct_d1_higher = (df['D1'] > df['AI']).mean()
pct_d2_higher = (df['D2'] > df['AI']).mean()
pct_d3_higher = (df['D3'] > df['AI']).mean()
print(f"Percent D1 > AI: {pct_d1_higher:.2%}, D2 > AI: {pct_d2_higher:.2%}, D3 > AI: {pct_d3_higher:.2%}")

# Number of essays where D3 > 0.5
print("Count human D3 >= 0.5:", (df['D3'] >= 0.5).sum())

N essays: 21
AI baseline score (fixed): 0.03659766302934076
Human D1 mean: 0.3345080911190356 std: 0.2434820481455787
Human D2 mean: 0.2832374700309689 std: 0.2409710600988789
Human D3 mean: 0.326353096482848 std: 0.2870733157389929
Percent D1 > AI: 85.71%, D2 > AI: 90.48%, D3 > AI: 90.48%
Count human D3 >= 0.5: 5

In [25]:
# Cell: select only essays where at least one transition is nonsemantic and verified
valid_df = df.copy()
# Use 'valid_12' and 'valid_23' columns (True if safe)
valid_df['any_valid_transition'] = valid_df[['valid_12','valid_23']].any(axis=1)

print("Total essays:", len(df))
print("Essays with at least one verified nonsemantic transition:", valid_df['any_valid_transition'].sum())

# Compute means on this subset
sub = valid_df[valid_df['any_valid_transition']]
print("Subset mean AI_to_D3:", (sub['D3'] - sub['AI']).mean())
print("Subset mean D1_to_D2 (only where valid):", sub.loc[sub['valid_12'],'D2'].mean() - sub.loc[sub['valid_12'],'D1'].mean())

Total essays: 21
Essays with at least one verified nonsemantic transition: 13
Subset mean AI_to_D3: 0.2470103228841541
Subset mean D1_to_D2 (only where valid): 0.007164573257668921

In [26]:
# Cell: Wilcoxon signed-rank and paired t-tests: D3 vs AI
from scipy.stats import wilcoxon, ttest_rel

d3_minus_ai = df['D3'] - df['AI']
print("Wilcoxon D3 vs AI p:", wilcoxon(d3_minus_ai).pvalue)
print("Paired t-test D3 vs AI p:", ttest_rel(df['D3'], df['AI']).pvalue)

# For only nonsemantic transitions (D3 if either valid23 or valid12? do D3 vs AI but only where any_valid_transition)
sub = df[df[['valid_12','valid_23']].any(axis=1)]
print("Wilcoxon on verified subset p:", wilcoxon(sub['D3'] - sub['AI']).pvalue)

Wilcoxon D3 vs AI p: 1.811981201171875e-05
Paired t-test D3 vs AI p: 0.00016341085838512528
Wilcoxon on verified subset p: 0.000244140625

In [27]:
# Cell: effect sizes
df['delta_AI_D3'] = df['D3'] - df['AI']
df_sorted = df.sort_values('delta_AI_D3', ascending=False)
df_sorted[['essay_id','AI','D1','D2','D3','delta_AI_D3']].head(10)

    essay_id        AI        D1        D2        D3  delta_AI_D3
16        74  0.036598  0.642085  0.855406  0.921645     0.885047
8         38  0.036598  0.900503  0.847998  0.888415     0.851817
5         20  0.036598  0.589516  0.454811  0.780920     0.744322
11        50  0.036598  0.235063  0.327674  0.567811     0.531214
6         23  0.036598  0.364797  0.339242  0.559170     0.522572
18        82  0.036598  0.151232  0.326227  0.465624     0.429026
2         14  0.036598  0.624233  0.385327  0.435338     0.398740
7         24  0.036598  0.451399  0.325455  0.400638     0.364041
10        46  0.036598  0.121937  0.096726  0.386088     0.349491
4         16  0.036598  0.415750  0.406901  0.322310     0.285712

In [29]:
# Cell: build labels and compute ROC
from sklearn.metrics import roc_curve, auc
# Build samples: AI (1 sample) + human D3s -> not ideal for ROC (unbalanced), but we can construct an empirical set by repeating the AI or generating a small ensemble.
# Better: compare distributions of AI score vs humans via rank tests (we did). But we can compute empirical sensitivity at thresholds.

human_scores = df['D3'].values
ai_score = df['AI'].iloc[0]

# Fraction of humans above a chosen threshold (e.g., 0.5)
for thr in [0.25,0.5,0.75]:
    print(f"Fraction of humans with score >= {thr}:", (human_scores >= thr).mean())

# Optionally, compute ROC by treating ai_score as a single positive and humans as negatives is unstable; instead compute ranks:
ranks = (human_scores > ai_score).sum()
print("Number of human drafts scoring higher than AI:", ranks)

Fraction of humans with score >= 0.25: 0.47619047619047616
Fraction of humans with score >= 0.5: 0.23809523809523808
Fraction of humans with score >= 0.75: 0.14285714285714285
Number of human drafts scoring higher than AI: 19

In [30]:
# Cell: print suspect essays
suspects = df.sort_values('delta_AI_D3', ascending=False).head(6)
for eid in suspects['essay_id']:
    print("=== essay", eid)
    print("D3 (first 800 chars):")
    print(load_text(D3 / f"2018argrewrite_{eid}.txt")[:800])
    print("\n----\n")

=== essay 74
D3 (first 800 chars):
Not having to worry about paying attention while driving is cool, but dying because your computerized, self-driven car made a mistake is not.
	Washington, D.C., Nevada, Florida, Michigan and California are testing cars with artificial intelligence, and they're proving that the hassle creates more danger than the convenience is worth. While it's shown that self-driving cars can prevent accidents caused by human drivers, they don't completely eliminate them and in fact, offer their own set of safety hazards.
	While car accidents account for a large portion of deaths in the United States, adding the unpredictability of self-driving cars' capabilities for safe driving only make matters more hazardous for everyone on the road. In addition to worrying if humans are capable to drive regular car

----

=== essay 38
D3 (first 800 chars):
Self-driving cars fuel some of the hottest debates in technology today. Proponents believe the cars should reduce accidents, free up drivers’ time, and make obsolete the need for detailed knowledge of driving, thus allowing people who could never use cars alone in the past (like the disabled and elderly) more freedom. Meanwhile, others worry that computers would not make decisions and adapt in the same manner as attentive human drivers, would provide more security risks, and would present a large potential for vehicle failure. I side with this latter group, and my main reasoning is that computers do not have as high an understanding of the world around them as humans.
	I actually have firsthand experience with a car equipped with simple self-driving capabilities. In April my parents and I

----

=== essay 20
D3 (first 800 chars):
The potential benefits of self-driving cars mentioned in the Auto Insurance Center article, "Top 20 Pros and Cons Associated with Self-Driving Cars," are significant: no need for a driving license, reduction of distracted driving, and more time for other activities while in the car. However, those benefits assume the car would be in control 100% of the time, which is not realistic. Operators need to be aware and prepared to take control in the event of an emergency. Without more conversation about the education that drivers would need to have to successfully operate self-driving cars and more research into privacy and safety, driver-less cars will not be as beneficial as some might think.
	The article lists not needing to get a driving license as an advantage of self-driving cars, but tha

----

=== essay 50
D3 (first 800 chars):
Technology remains to be the backbone of civilizations. Over the years, most societies developed new, innovative ideas to make the human experience easier and more efficient. Now, in the age of the technological boom, innovators race for new patents and ideas that could have not have been dreamed about by past societies. For instance, hover boards are essentially skateboards that are motorized, which should have been a new frontier for toy technology. However, hover boards are actually used to entertain the public with their spectacular, flaming explosions on the internet. Does the self-driving car have the same fiery fate? I believe the self-driving car will end up having more positive qualities than negative qualities due to its inherent potential.
	For starters, this technology can add

----

=== essay 23
D3 (first 800 chars):
As technology continues to progress at a rapid pace innovators have begun to explore the possibility of self-driving cars. A society with self-driving cars sounds like a child's response to the question "What does the future look like". Self-driving cars evoke fantastical thoughts of what a futuristic Utopian society looks like. However, self-driving cars are no longer a fantasy idea, and the impact that these vehicles may have on society is immense. To many in society, the term "self-driving cars" is synonymous with complete leisure . With a self-driving car there is no need to be stressed driving or road rage because something else is in charge of the wheel. There are notions that self-driving cars could help to limit accidents due to the fact that they take away the human error of drivi

----

=== essay 82
D3 (first 800 chars):
Do you remember childhood car rides spent gazing out the window, reading, and sleeping? Those experiences were always thought of as the "good old days", but they can become a reality once again. Self-driving cars are the next creation for the future. Pioneered by Google, self driving cars have been created to allow for a safer and more enjoyable transportation experience. However, there are numerous areas for potential problems that could make these cars less efficient and ultimately more dangerous on the road. It is important to explore both sides of this creation, but despite the positive aspects, it is clear that self-driving cars will not benefit society as much as they are projected to. Throughout this essay the benefits, drawbacks, and overall conclusion regarding self-driving cars,

----

In [28]:
# Cell: compute length and simple features
import re
def char_len(s): return len(s)
def token_count(s): return len(s.split())
def avg_word_len(s): return np.mean([len(w) for w in s.split()]) if s.strip() else 0
def comma_rate(s): return s.count(',') / max(1,len(s.split()))
def question_rate(s): return s.count('?') / max(1,len(s.split()))

for col in ['D1','D2','D3']:
    df[f'{col}_chars'] = df[col].apply(lambda x: char_len(x))
    df[f'{col}_tokens'] = df[col].apply(lambda x: token_count(x))
    df[f'{col}_avgwl'] = df[col].apply(lambda x: avg_word_len(x))

# Correlations with D3 score
print("Spearman corr D3 score vs D3 length:", df['D3'].corr(df['D3_chars'], method='spearman'))
print("Spearman corr D3 score vs D3 avg word len:", df['D3'].corr(df['D3_avgwl'], method='spearman'))

TypeError: object of type 'float' has no len()